// This file is auto-generated by @hey-api/openapi-ts

export const ObjectSchema = {
  type: 'object',
} as const;

export const TaxonomyReferenceResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: 'string',
    },
  },
  required: ['id', 'name'],
} as const;

export const LinkSourceResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    chatId: {
      type: 'string',
      format: 'uuid',
    },
    chatName: {
      type: 'string',
    },
    messageId: {
      type: 'number',
    },
    messagePreview: {
      type: 'string',
    },
    messageText: {
      type: 'string',
    },
    messageUrl: {
      type: 'object',
      nullable: true,
    },
    rawUrl: {
      type: 'string',
    },
    senderName: {
      type: 'object',
      nullable: true,
    },
    capturedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: [
    'id',
    'chatId',
    'chatName',
    'messageId',
    'messagePreview',
    'rawUrl',
    'capturedAt',
  ],
} as const;

export const LinkResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    domain: {
      type: 'string',
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    project: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
        },
      ],
    },
    category: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
        },
      ],
    },
    tags: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
      },
    },
    purpose: {
      type: 'object',
      nullable: true,
    },
    isFavorite: {
      type: 'boolean',
    },
    sourceCount: {
      type: 'number',
    },
    latestSource: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/LinkSourceResponseDto',
        },
      ],
    },
    sources: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/LinkSourceResponseDto',
      },
    },
    firstDiscoveredAt: {
      type: 'string',
      format: 'date-time',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
    archivedAt: {
      type: 'object',
      format: 'date-time',
      nullable: true,
    },
  },
  required: [
    'id',
    'title',
    'url',
    'domain',
    'environment',
    'status',
    'project',
    'category',
    'tags',
    'purpose',
    'isFavorite',
    'sourceCount',
    'latestSource',
    'firstDiscoveredAt',
    'createdAt',
    'updatedAt',
    'archivedAt',
  ],
} as const;

export const PaginationMetaResponseDtoSchema = {
  type: 'object',
  properties: {
    page: {
      type: 'number',
    },
    pageSize: {
      type: 'number',
    },
    total: {
      type: 'number',
    },
    totalPages: {
      type: 'number',
    },
  },
  required: ['page', 'pageSize', 'total', 'totalPages'],
} as const;

export const PaginatedLinksResponseDtoSchema = {
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/LinkResponseDto',
      },
    },
    pagination: {
      $ref: '#/components/schemas/PaginationMetaResponseDto',
    },
  },
  required: ['items', 'pagination'],
} as const;

export const BatchLinkPatchDtoSchema = {
  type: 'object',
  properties: {
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    purpose: {
      type: 'object',
      nullable: true,
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    projectId: {
      type: 'object',
      format: 'uuid',
      nullable: true,
    },
    categoryId: {
      type: 'object',
      format: 'uuid',
      nullable: true,
    },
    tagIds: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
    isFavorite: {
      type: 'boolean',
    },
    addTagIds: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
  },
} as const;

export const BatchUpdateLinksDtoSchema = {
  type: 'object',
  properties: {
    ids: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
    patch: {
      $ref: '#/components/schemas/BatchLinkPatchDto',
    },
  },
  required: ['ids', 'patch'],
} as const;

export const UpdateLinkDtoSchema = {
  type: 'object',
  properties: {
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    purpose: {
      type: 'object',
      nullable: true,
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    projectId: {
      type: 'object',
      format: 'uuid',
      nullable: true,
    },
    categoryId: {
      type: 'object',
      format: 'uuid',
      nullable: true,
    },
    tagIds: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
    isFavorite: {
      type: 'boolean',
    },
  },
} as const;

export const CreateSyncJobDtoSchema = {
  type: 'object',
  properties: {
    chatIds: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
    rangeMode: {
      type: 'string',
      enum: ['sinceLast', 'last7Days', 'custom', 'allHistory'],
    },
    rangeFrom: {
      format: 'date-time',
      type: 'string',
    },
    rangeTo: {
      format: 'date-time',
      type: 'string',
    },
    defaultProjectId: {
      type: 'string',
      format: 'uuid',
    },
    defaultCategoryId: {
      type: 'string',
      format: 'uuid',
    },
    defaultTagIds: {
      type: 'array',
      items: {
        type: 'array',
        format: 'uuid',
      },
    },
  },
  required: ['rangeMode'],
} as const;

export const TaxonomyNameDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
  },
  required: ['name'],
} as const;

export const SendCodeDtoSchema = {
  type: 'object',
  properties: {
    phoneNumber: {
      type: 'string',
      example: '+8613800000000',
    },
  },
  required: ['phoneNumber'],
} as const;

export const VerifyCodeDtoSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['challengeId'],
} as const;

export const VerifyPasswordDtoSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['challengeId'],
} as const;

export const UpdateChatDtoSchema = {
  type: 'object',
  properties: {
    isEnabled: {
      type: 'boolean',
    },
  },
  required: ['isEnabled'],
} as const;

export const ObjectWritableSchema = {
  type: 'object',
} as const;

export const VerifyCodeDtoWritableSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
    code: {
      type: 'string',
      writeOnly: true,
    },
  },
  required: ['challengeId', 'code'],
} as const;

export const VerifyPasswordDtoWritableSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
    password: {
      type: 'string',
      writeOnly: true,
    },
  },
  required: ['challengeId', 'password'],
} as const;
