// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AdminLinksControllerArchiveData,
  AdminLinksControllerArchiveResponses,
  AdminLinksControllerBatchData,
  AdminLinksControllerBatchResponses,
  AdminLinksControllerFindOneData,
  AdminLinksControllerFindOneResponses,
  AdminLinksControllerListData,
  AdminLinksControllerListResponses,
  AdminLinksControllerOverviewData,
  AdminLinksControllerOverviewResponses,
  AdminLinksControllerRestoreData,
  AdminLinksControllerRestoreResponses,
  AdminLinksControllerUpdateData,
  AdminLinksControllerUpdateResponses,
  AdminSyncControllerCreateData,
  AdminSyncControllerCreateResponses,
  AdminSyncControllerFindOneData,
  AdminSyncControllerFindOneResponses,
  AdminSyncControllerListData,
  AdminSyncControllerListResponses,
  AdminTaxonomyControllerCreateData,
  AdminTaxonomyControllerCreateResponses,
  AdminTaxonomyControllerListData,
  AdminTaxonomyControllerListResponses,
  AdminTaxonomyControllerRemoveData,
  AdminTaxonomyControllerRemoveResponses,
  AdminTaxonomyControllerRenameData,
  AdminTaxonomyControllerRenameResponses,
  AdminTelegramControllerAccountData,
  AdminTelegramControllerAccountResponses,
  AdminTelegramControllerListChatsData,
  AdminTelegramControllerListChatsResponses,
  AdminTelegramControllerLogOutData,
  AdminTelegramControllerLogOutResponses,
  AdminTelegramControllerRefreshChatsData,
  AdminTelegramControllerRefreshChatsResponses,
  AdminTelegramControllerSendCodeData,
  AdminTelegramControllerSendCodeResponses,
  AdminTelegramControllerUpdateChatData,
  AdminTelegramControllerUpdateChatResponses,
  AdminTelegramControllerVerifyCodeData,
  AdminTelegramControllerVerifyCodeResponses,
  AdminTelegramControllerVerifyPasswordData,
  AdminTelegramControllerVerifyPasswordResponses,
} from './types.gen';
import {
  zAdminLinksControllerArchiveResponse,
  zAdminLinksControllerFindOneResponse,
  zAdminLinksControllerListResponse,
  zAdminLinksControllerRestoreResponse,
  zAdminLinksControllerUpdateResponse,
  zAdminTaxonomyControllerRemoveResponse,
  zAdminTelegramControllerLogOutResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const adminLinksControllerOverview = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminLinksControllerOverviewData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerOverviewResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminLinksControllerOverviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/overview', ...options });

export const adminLinksControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminLinksControllerListData, ThrowOnError>,
): RequestResult<AdminLinksControllerListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AdminLinksControllerListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerListResponse.parseAsync(data),
    url: '/api/admin/v1/links',
    ...options,
  });

export const adminLinksControllerBatch = <ThrowOnError extends boolean = false>(
  options: Options<AdminLinksControllerBatchData, ThrowOnError>,
): RequestResult<AdminLinksControllerBatchResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<
    AdminLinksControllerBatchResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/links/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerArchive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerArchiveData, ThrowOnError>,
): RequestResult<AdminLinksControllerArchiveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    AdminLinksControllerArchiveResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminLinksControllerArchiveResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerFindOneData, ThrowOnError>,
): RequestResult<AdminLinksControllerFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    AdminLinksControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerFindOneResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerUpdateData, ThrowOnError>,
): RequestResult<AdminLinksControllerUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<
    AdminLinksControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerUpdateResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerRestoreData, ThrowOnError>,
): RequestResult<AdminLinksControllerRestoreResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    AdminLinksControllerRestoreResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerRestoreResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}/restore',
    ...options,
  });

export const adminSyncControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminSyncControllerListData, ThrowOnError>,
): RequestResult<AdminSyncControllerListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AdminSyncControllerListResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/sync-jobs', ...options });

export const adminSyncControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<AdminSyncControllerCreateData, ThrowOnError>,
): RequestResult<AdminSyncControllerCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    AdminSyncControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/sync-jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminSyncControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminSyncControllerFindOneData, ThrowOnError>,
): RequestResult<AdminSyncControllerFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    AdminSyncControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/sync-jobs/{id}', ...options });

export const adminTaxonomyControllerList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerListData, ThrowOnError>,
): RequestResult<AdminTaxonomyControllerListResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    AdminTaxonomyControllerListResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/taxonomy/{kind}', ...options });

export const adminTaxonomyControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerCreateResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTaxonomyControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/taxonomy/{kind}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTaxonomyControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRemoveData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRemoveResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminTaxonomyControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerRemoveResponse.parseAsync(data),
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
  });

export const adminTaxonomyControllerRename = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRenameData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRenameResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminTaxonomyControllerRenameResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerAccount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerAccountData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerAccountResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerAccountResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/telegram/account', ...options });

export const adminTelegramControllerSendCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerSendCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerSendCodeResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerSendCodeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/telegram/auth/code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyCodeResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyCodeResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/telegram/auth/code/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyPasswordData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyPasswordResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/telegram/auth/password/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerLogOut = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerLogOutData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerLogOutResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AdminTelegramControllerLogOutResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTelegramControllerLogOutResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/session',
    ...options,
  });

export const adminTelegramControllerRefreshChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerRefreshChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerRefreshChatsResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    AdminTelegramControllerRefreshChatsResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/telegram/chats/refresh', ...options });

export const adminTelegramControllerListChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerListChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerListChatsResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerListChatsResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/admin/v1/telegram/chats', ...options });

export const adminTelegramControllerUpdateChat = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerUpdateChatData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerUpdateChatResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminTelegramControllerUpdateChatResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/v1/telegram/chats/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
