// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AdminAuthControllerLoginData,
  AdminAuthControllerLoginErrors,
  AdminAuthControllerLoginResponses,
  AdminAuthControllerLogoutData,
  AdminAuthControllerLogoutResponses,
  AdminAuthControllerSessionData,
  AdminAuthControllerSessionResponses,
  AdminLinksControllerArchiveData,
  AdminLinksControllerArchiveErrors,
  AdminLinksControllerArchiveResponses,
  AdminLinksControllerBatchArchiveData,
  AdminLinksControllerBatchArchiveErrors,
  AdminLinksControllerBatchArchiveResponses,
  AdminLinksControllerBatchData,
  AdminLinksControllerBatchErrors,
  AdminLinksControllerBatchResponses,
  AdminLinksControllerCreateData,
  AdminLinksControllerCreateErrors,
  AdminLinksControllerCreateResponses,
  AdminLinksControllerFindOneData,
  AdminLinksControllerFindOneErrors,
  AdminLinksControllerFindOneResponses,
  AdminLinksControllerListData,
  AdminLinksControllerListErrors,
  AdminLinksControllerListResponses,
  AdminLinksControllerOverviewData,
  AdminLinksControllerOverviewErrors,
  AdminLinksControllerOverviewResponses,
  AdminLinksControllerRestoreData,
  AdminLinksControllerRestoreErrors,
  AdminLinksControllerRestoreResponses,
  AdminLinksControllerUpdateData,
  AdminLinksControllerUpdateErrors,
  AdminLinksControllerUpdateResponses,
  AdminSyncControllerCreateData,
  AdminSyncControllerCreateErrors,
  AdminSyncControllerCreateResponses,
  AdminSyncControllerFindOneData,
  AdminSyncControllerFindOneErrors,
  AdminSyncControllerFindOneResponses,
  AdminSyncControllerListData,
  AdminSyncControllerListErrors,
  AdminSyncControllerListResponses,
  AdminTaxonomyControllerCreateData,
  AdminTaxonomyControllerCreateErrors,
  AdminTaxonomyControllerCreateResponses,
  AdminTaxonomyControllerListData,
  AdminTaxonomyControllerListErrors,
  AdminTaxonomyControllerListResponses,
  AdminTaxonomyControllerRemoveData,
  AdminTaxonomyControllerRemoveErrors,
  AdminTaxonomyControllerRemoveResponses,
  AdminTaxonomyControllerRenameData,
  AdminTaxonomyControllerRenameErrors,
  AdminTaxonomyControllerRenameResponses,
  AdminTaxonomyControllerReorderData,
  AdminTaxonomyControllerReorderErrors,
  AdminTaxonomyControllerReorderResponses,
  AdminTelegramControllerAccountData,
  AdminTelegramControllerAccountErrors,
  AdminTelegramControllerAccountResponses,
  AdminTelegramControllerListChatsData,
  AdminTelegramControllerListChatsErrors,
  AdminTelegramControllerListChatsResponses,
  AdminTelegramControllerLogOutData,
  AdminTelegramControllerLogOutErrors,
  AdminTelegramControllerLogOutResponses,
  AdminTelegramControllerRefreshChatsData,
  AdminTelegramControllerRefreshChatsErrors,
  AdminTelegramControllerRefreshChatsResponses,
  AdminTelegramControllerScanOptionsData,
  AdminTelegramControllerScanOptionsErrors,
  AdminTelegramControllerScanOptionsResponses,
  AdminTelegramControllerSendCodeData,
  AdminTelegramControllerSendCodeErrors,
  AdminTelegramControllerSendCodeResponses,
  AdminTelegramControllerVerifyCodeData,
  AdminTelegramControllerVerifyCodeErrors,
  AdminTelegramControllerVerifyCodeResponses,
  AdminTelegramControllerVerifyPasswordData,
  AdminTelegramControllerVerifyPasswordErrors,
  AdminTelegramControllerVerifyPasswordResponses,
} from './types.gen';
import {
  zAdminAuthControllerLoginResponse,
  zAdminAuthControllerLogoutResponse,
  zAdminAuthControllerSessionResponse,
  zAdminLinksControllerArchiveResponse,
  zAdminLinksControllerBatchArchiveResponse,
  zAdminLinksControllerBatchResponse,
  zAdminLinksControllerCreateResponse,
  zAdminLinksControllerFindOneResponse,
  zAdminLinksControllerListResponse,
  zAdminLinksControllerOverviewResponse,
  zAdminLinksControllerRestoreResponse,
  zAdminLinksControllerUpdateResponse,
  zAdminSyncControllerCreateResponse,
  zAdminSyncControllerFindOneResponse,
  zAdminSyncControllerListResponse,
  zAdminTaxonomyControllerCreateResponse,
  zAdminTaxonomyControllerListResponse,
  zAdminTaxonomyControllerRemoveResponse,
  zAdminTaxonomyControllerRenameResponse,
  zAdminTaxonomyControllerReorderResponse,
  zAdminTelegramControllerAccountResponse,
  zAdminTelegramControllerListChatsResponse,
  zAdminTelegramControllerLogOutResponse,
  zAdminTelegramControllerRefreshChatsResponse,
  zAdminTelegramControllerScanOptionsResponse,
  zAdminTelegramControllerSendCodeResponse,
  zAdminTelegramControllerVerifyCodeResponse,
  zAdminTelegramControllerVerifyPasswordResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const adminAuthControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAuthControllerLogoutData, ThrowOnError>,
): RequestResult<AdminAuthControllerLogoutResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).delete<
    AdminAuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminAuthControllerLogoutResponse.parseAsync(data),
    url: '/api/admin/v1/auth/session',
    ...options,
  });

export const adminAuthControllerSession = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminAuthControllerSessionData, ThrowOnError>,
): RequestResult<AdminAuthControllerSessionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AdminAuthControllerSessionResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAuthControllerSessionResponse.parseAsync(data),
    url: '/api/admin/v1/auth/session',
    ...options,
  });

export const adminAuthControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AdminAuthControllerLoginData, ThrowOnError>,
): RequestResult<
  AdminAuthControllerLoginResponses,
  AdminAuthControllerLoginErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminAuthControllerLoginResponses,
    AdminAuthControllerLoginErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAuthControllerLoginResponse.parseAsync(data),
    url: '/api/admin/v1/auth/session',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerOverview = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminLinksControllerOverviewData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerOverviewResponses,
  AdminLinksControllerOverviewErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminLinksControllerOverviewResponses,
    AdminLinksControllerOverviewErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerOverviewResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/overview',
    ...options,
  });

export const adminLinksControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminLinksControllerListData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerListResponses,
  AdminLinksControllerListErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminLinksControllerListResponses,
    AdminLinksControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerListResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links',
    ...options,
  });

export const adminLinksControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerCreateResponses,
  AdminLinksControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminLinksControllerCreateResponses,
    AdminLinksControllerCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerCreateResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerBatch = <ThrowOnError extends boolean = false>(
  options: Options<AdminLinksControllerBatchData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerBatchResponses,
  AdminLinksControllerBatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminLinksControllerBatchResponses,
    AdminLinksControllerBatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerBatchResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerBatchArchive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerBatchArchiveData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerBatchArchiveResponses,
  AdminLinksControllerBatchArchiveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminLinksControllerBatchArchiveResponses,
    AdminLinksControllerBatchArchiveErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerBatchArchiveResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/batch/archive',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerArchive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerArchiveData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerArchiveResponses,
  AdminLinksControllerArchiveErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminLinksControllerArchiveResponses,
    AdminLinksControllerArchiveErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminLinksControllerArchiveResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerFindOneData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerFindOneResponses,
  AdminLinksControllerFindOneErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminLinksControllerFindOneResponses,
    AdminLinksControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerFindOneResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerUpdateData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerUpdateResponses,
  AdminLinksControllerUpdateErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminLinksControllerUpdateResponses,
    AdminLinksControllerUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerUpdateResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerRestoreData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerRestoreResponses,
  AdminLinksControllerRestoreErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminLinksControllerRestoreResponses,
    AdminLinksControllerRestoreErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerRestoreResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/links/{id}/restore',
    ...options,
  });

export const adminSyncControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminSyncControllerListData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerListResponses,
  AdminSyncControllerListErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminSyncControllerListResponses,
    AdminSyncControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerListResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/sync-jobs',
    ...options,
  });

export const adminSyncControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<AdminSyncControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerCreateResponses,
  AdminSyncControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminSyncControllerCreateResponses,
    AdminSyncControllerCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerCreateResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/sync-jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminSyncControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminSyncControllerFindOneData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerFindOneResponses,
  AdminSyncControllerFindOneErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminSyncControllerFindOneResponses,
    AdminSyncControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerFindOneResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/sync-jobs/{id}',
    ...options,
  });

export const adminTaxonomyControllerList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerListData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerListResponses,
  AdminTaxonomyControllerListErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminTaxonomyControllerListResponses,
    AdminTaxonomyControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerListResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/taxonomy/{kind}',
    ...options,
  });

export const adminTaxonomyControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerCreateResponses,
  AdminTaxonomyControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTaxonomyControllerCreateResponses,
    AdminTaxonomyControllerCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerCreateResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/taxonomy/{kind}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTaxonomyControllerReorder = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerReorderData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerReorderResponses,
  AdminTaxonomyControllerReorderErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    AdminTaxonomyControllerReorderResponses,
    AdminTaxonomyControllerReorderErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerReorderResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/taxonomy/{kind}/order',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTaxonomyControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRemoveData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRemoveResponses,
  AdminTaxonomyControllerRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminTaxonomyControllerRemoveResponses,
    AdminTaxonomyControllerRemoveErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerRemoveResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
  });

export const adminTaxonomyControllerRename = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRenameData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRenameResponses,
  AdminTaxonomyControllerRenameErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminTaxonomyControllerRenameResponses,
    AdminTaxonomyControllerRenameErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerRenameResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerAccount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerAccountData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerAccountResponses,
  AdminTelegramControllerAccountErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerAccountResponses,
    AdminTelegramControllerAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerAccountResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/account',
    ...options,
  });

export const adminTelegramControllerSendCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerSendCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerSendCodeResponses,
  AdminTelegramControllerSendCodeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerSendCodeResponses,
    AdminTelegramControllerSendCodeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerSendCodeResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/auth/code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyCodeResponses,
  AdminTelegramControllerVerifyCodeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyCodeResponses,
    AdminTelegramControllerVerifyCodeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerVerifyCodeResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/auth/code/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyPasswordData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyPasswordResponses,
  AdminTelegramControllerVerifyPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyPasswordResponses,
    AdminTelegramControllerVerifyPasswordErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerVerifyPasswordResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/auth/password/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerLogOut = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerLogOutData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerLogOutResponses,
  AdminTelegramControllerLogOutErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AdminTelegramControllerLogOutResponses,
    AdminTelegramControllerLogOutErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTelegramControllerLogOutResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/session',
    ...options,
  });

export const adminTelegramControllerRefreshChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerRefreshChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerRefreshChatsResponses,
  AdminTelegramControllerRefreshChatsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    AdminTelegramControllerRefreshChatsResponses,
    AdminTelegramControllerRefreshChatsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerRefreshChatsResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/chats/refresh',
    ...options,
  });

export const adminTelegramControllerListChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerListChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerListChatsResponses,
  AdminTelegramControllerListChatsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerListChatsResponses,
    AdminTelegramControllerListChatsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerListChatsResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/chats',
    ...options,
  });

export const adminTelegramControllerScanOptions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerScanOptionsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerScanOptionsResponses,
  AdminTelegramControllerScanOptionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerScanOptionsResponses,
    AdminTelegramControllerScanOptionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerScanOptionsResponse.parseAsync(data),
    security: [
      {
        in: 'cookie',
        name: 'telegram_links_admin_session',
        type: 'apiKey',
      },
    ],
    url: '/api/admin/v1/telegram/chats/scan-options',
    ...options,
  });
