// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AdminAiControllerClearKeyData,
  AdminAiControllerClearKeyErrors,
  AdminAiControllerClearKeyResponses,
  AdminAiControllerModelsData,
  AdminAiControllerModelsErrors,
  AdminAiControllerModelsResponses,
  AdminAiControllerSetKeyData,
  AdminAiControllerSetKeyErrors,
  AdminAiControllerSetKeyResponses,
  AdminAiControllerSetModelData,
  AdminAiControllerSetModelErrors,
  AdminAiControllerSetModelResponses,
  AdminAiControllerSettingsData,
  AdminAiControllerSettingsErrors,
  AdminAiControllerSettingsResponses,
  AdminLinksControllerApplyAiSuggestionsData,
  AdminLinksControllerApplyAiSuggestionsErrors,
  AdminLinksControllerApplyAiSuggestionsResponses,
  AdminLinksControllerArchiveData,
  AdminLinksControllerArchiveErrors,
  AdminLinksControllerArchiveResponses,
  AdminLinksControllerBatchData,
  AdminLinksControllerBatchErrors,
  AdminLinksControllerBatchResponses,
  AdminLinksControllerFindOneData,
  AdminLinksControllerFindOneErrors,
  AdminLinksControllerFindOneResponses,
  AdminLinksControllerListData,
  AdminLinksControllerListErrors,
  AdminLinksControllerListResponses,
  AdminLinksControllerOverviewData,
  AdminLinksControllerOverviewErrors,
  AdminLinksControllerOverviewResponses,
  AdminLinksControllerRestoreData,
  AdminLinksControllerRestoreErrors,
  AdminLinksControllerRestoreResponses,
  AdminLinksControllerUpdateData,
  AdminLinksControllerUpdateErrors,
  AdminLinksControllerUpdateResponses,
  AdminSyncControllerCreateData,
  AdminSyncControllerCreateErrors,
  AdminSyncControllerCreateResponses,
  AdminSyncControllerFindOneData,
  AdminSyncControllerFindOneErrors,
  AdminSyncControllerFindOneResponses,
  AdminSyncControllerListData,
  AdminSyncControllerListErrors,
  AdminSyncControllerListResponses,
  AdminTaxonomyControllerCreateData,
  AdminTaxonomyControllerCreateErrors,
  AdminTaxonomyControllerCreateResponses,
  AdminTaxonomyControllerListData,
  AdminTaxonomyControllerListErrors,
  AdminTaxonomyControllerListResponses,
  AdminTaxonomyControllerRemoveData,
  AdminTaxonomyControllerRemoveErrors,
  AdminTaxonomyControllerRemoveResponses,
  AdminTaxonomyControllerRenameData,
  AdminTaxonomyControllerRenameErrors,
  AdminTaxonomyControllerRenameResponses,
  AdminTelegramControllerAccountData,
  AdminTelegramControllerAccountErrors,
  AdminTelegramControllerAccountResponses,
  AdminTelegramControllerListChatsData,
  AdminTelegramControllerListChatsErrors,
  AdminTelegramControllerListChatsResponses,
  AdminTelegramControllerLogOutData,
  AdminTelegramControllerLogOutErrors,
  AdminTelegramControllerLogOutResponses,
  AdminTelegramControllerRefreshChatsData,
  AdminTelegramControllerRefreshChatsErrors,
  AdminTelegramControllerRefreshChatsResponses,
  AdminTelegramControllerScanOptionsData,
  AdminTelegramControllerScanOptionsErrors,
  AdminTelegramControllerScanOptionsResponses,
  AdminTelegramControllerSendCodeData,
  AdminTelegramControllerSendCodeErrors,
  AdminTelegramControllerSendCodeResponses,
  AdminTelegramControllerVerifyCodeData,
  AdminTelegramControllerVerifyCodeErrors,
  AdminTelegramControllerVerifyCodeResponses,
  AdminTelegramControllerVerifyPasswordData,
  AdminTelegramControllerVerifyPasswordErrors,
  AdminTelegramControllerVerifyPasswordResponses,
} from './types.gen';
import {
  zAdminAiControllerClearKeyResponse,
  zAdminAiControllerModelsResponse,
  zAdminAiControllerSetKeyResponse,
  zAdminAiControllerSetModelResponse,
  zAdminAiControllerSettingsResponse,
  zAdminLinksControllerApplyAiSuggestionsResponse,
  zAdminLinksControllerArchiveResponse,
  zAdminLinksControllerBatchResponse,
  zAdminLinksControllerFindOneResponse,
  zAdminLinksControllerListResponse,
  zAdminLinksControllerOverviewResponse,
  zAdminLinksControllerRestoreResponse,
  zAdminLinksControllerUpdateResponse,
  zAdminSyncControllerCreateResponse,
  zAdminSyncControllerFindOneResponse,
  zAdminSyncControllerListResponse,
  zAdminTaxonomyControllerCreateResponse,
  zAdminTaxonomyControllerListResponse,
  zAdminTaxonomyControllerRemoveResponse,
  zAdminTaxonomyControllerRenameResponse,
  zAdminTelegramControllerAccountResponse,
  zAdminTelegramControllerListChatsResponse,
  zAdminTelegramControllerLogOutResponse,
  zAdminTelegramControllerRefreshChatsResponse,
  zAdminTelegramControllerScanOptionsResponse,
  zAdminTelegramControllerSendCodeResponse,
  zAdminTelegramControllerVerifyCodeResponse,
  zAdminTelegramControllerVerifyPasswordResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const adminAiControllerSettings = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAiControllerSettingsData, ThrowOnError>,
): RequestResult<
  AdminAiControllerSettingsResponses,
  AdminAiControllerSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminAiControllerSettingsResponses,
    AdminAiControllerSettingsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAiControllerSettingsResponse.parseAsync(data),
    url: '/api/admin/v1/ai/settings',
    ...options,
  });

export const adminAiControllerClearKey = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAiControllerClearKeyData, ThrowOnError>,
): RequestResult<
  AdminAiControllerClearKeyResponses,
  AdminAiControllerClearKeyErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AdminAiControllerClearKeyResponses,
    AdminAiControllerClearKeyErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminAiControllerClearKeyResponse.parseAsync(data),
    url: '/api/admin/v1/ai/settings/key',
    ...options,
  });

export const adminAiControllerSetKey = <ThrowOnError extends boolean = false>(
  options: Options<AdminAiControllerSetKeyData, ThrowOnError>,
): RequestResult<
  AdminAiControllerSetKeyResponses,
  AdminAiControllerSetKeyErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    AdminAiControllerSetKeyResponses,
    AdminAiControllerSetKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAiControllerSetKeyResponse.parseAsync(data),
    url: '/api/admin/v1/ai/settings/key',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminAiControllerModels = <ThrowOnError extends boolean = false>(
  options?: Options<AdminAiControllerModelsData, ThrowOnError>,
): RequestResult<
  AdminAiControllerModelsResponses,
  AdminAiControllerModelsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminAiControllerModelsResponses,
    AdminAiControllerModelsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAiControllerModelsResponse.parseAsync(data),
    url: '/api/admin/v1/ai/models',
    ...options,
  });

export const adminAiControllerSetModel = <ThrowOnError extends boolean = false>(
  options: Options<AdminAiControllerSetModelData, ThrowOnError>,
): RequestResult<
  AdminAiControllerSetModelResponses,
  AdminAiControllerSetModelErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    AdminAiControllerSetModelResponses,
    AdminAiControllerSetModelErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminAiControllerSetModelResponse.parseAsync(data),
    url: '/api/admin/v1/ai/settings/model',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerOverview = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminLinksControllerOverviewData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerOverviewResponses,
  AdminLinksControllerOverviewErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminLinksControllerOverviewResponses,
    AdminLinksControllerOverviewErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerOverviewResponse.parseAsync(data),
    url: '/api/admin/v1/overview',
    ...options,
  });

export const adminLinksControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminLinksControllerListData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerListResponses,
  AdminLinksControllerListErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminLinksControllerListResponses,
    AdminLinksControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerListResponse.parseAsync(data),
    url: '/api/admin/v1/links',
    ...options,
  });

export const adminLinksControllerBatch = <ThrowOnError extends boolean = false>(
  options: Options<AdminLinksControllerBatchData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerBatchResponses,
  AdminLinksControllerBatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminLinksControllerBatchResponses,
    AdminLinksControllerBatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerBatchResponse.parseAsync(data),
    url: '/api/admin/v1/links/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerArchive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerArchiveData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerArchiveResponses,
  AdminLinksControllerArchiveErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminLinksControllerArchiveResponses,
    AdminLinksControllerArchiveErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminLinksControllerArchiveResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerFindOneData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerFindOneResponses,
  AdminLinksControllerFindOneErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminLinksControllerFindOneResponses,
    AdminLinksControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerFindOneResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
  });

export const adminLinksControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerUpdateData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerUpdateResponses,
  AdminLinksControllerUpdateErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminLinksControllerUpdateResponses,
    AdminLinksControllerUpdateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerUpdateResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminLinksControllerRestore = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerRestoreData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerRestoreResponses,
  AdminLinksControllerRestoreErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminLinksControllerRestoreResponses,
    AdminLinksControllerRestoreErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerRestoreResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}/restore',
    ...options,
  });

export const adminLinksControllerApplyAiSuggestions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminLinksControllerApplyAiSuggestionsData, ThrowOnError>,
): RequestResult<
  AdminLinksControllerApplyAiSuggestionsResponses,
  AdminLinksControllerApplyAiSuggestionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminLinksControllerApplyAiSuggestionsResponses,
    AdminLinksControllerApplyAiSuggestionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminLinksControllerApplyAiSuggestionsResponse.parseAsync(data),
    url: '/api/admin/v1/links/{id}/ai-suggestions/apply',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminSyncControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<AdminSyncControllerListData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerListResponses,
  AdminSyncControllerListErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminSyncControllerListResponses,
    AdminSyncControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerListResponse.parseAsync(data),
    url: '/api/admin/v1/sync-jobs',
    ...options,
  });

export const adminSyncControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<AdminSyncControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerCreateResponses,
  AdminSyncControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminSyncControllerCreateResponses,
    AdminSyncControllerCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerCreateResponse.parseAsync(data),
    url: '/api/admin/v1/sync-jobs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminSyncControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminSyncControllerFindOneData, ThrowOnError>,
): RequestResult<
  AdminSyncControllerFindOneResponses,
  AdminSyncControllerFindOneErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminSyncControllerFindOneResponses,
    AdminSyncControllerFindOneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminSyncControllerFindOneResponse.parseAsync(data),
    url: '/api/admin/v1/sync-jobs/{id}',
    ...options,
  });

export const adminTaxonomyControllerList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerListData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerListResponses,
  AdminTaxonomyControllerListErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    AdminTaxonomyControllerListResponses,
    AdminTaxonomyControllerListErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerListResponse.parseAsync(data),
    url: '/api/admin/v1/taxonomy/{kind}',
    ...options,
  });

export const adminTaxonomyControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerCreateData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerCreateResponses,
  AdminTaxonomyControllerCreateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTaxonomyControllerCreateResponses,
    AdminTaxonomyControllerCreateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerCreateResponse.parseAsync(data),
    url: '/api/admin/v1/taxonomy/{kind}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTaxonomyControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRemoveData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRemoveResponses,
  AdminTaxonomyControllerRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    AdminTaxonomyControllerRemoveResponses,
    AdminTaxonomyControllerRemoveErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerRemoveResponse.parseAsync(data),
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
  });

export const adminTaxonomyControllerRename = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTaxonomyControllerRenameData, ThrowOnError>,
): RequestResult<
  AdminTaxonomyControllerRenameResponses,
  AdminTaxonomyControllerRenameErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    AdminTaxonomyControllerRenameResponses,
    AdminTaxonomyControllerRenameErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTaxonomyControllerRenameResponse.parseAsync(data),
    url: '/api/admin/v1/taxonomy/{kind}/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerAccount = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerAccountData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerAccountResponses,
  AdminTelegramControllerAccountErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerAccountResponses,
    AdminTelegramControllerAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerAccountResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/account',
    ...options,
  });

export const adminTelegramControllerSendCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerSendCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerSendCodeResponses,
  AdminTelegramControllerSendCodeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerSendCodeResponses,
    AdminTelegramControllerSendCodeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerSendCodeResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/auth/code',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyCodeData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyCodeResponses,
  AdminTelegramControllerVerifyCodeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyCodeResponses,
    AdminTelegramControllerVerifyCodeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerVerifyCodeResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/auth/code/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerVerifyPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AdminTelegramControllerVerifyPasswordData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerVerifyPasswordResponses,
  AdminTelegramControllerVerifyPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AdminTelegramControllerVerifyPasswordResponses,
    AdminTelegramControllerVerifyPasswordErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerVerifyPasswordResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/auth/password/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const adminTelegramControllerLogOut = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerLogOutData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerLogOutResponses,
  AdminTelegramControllerLogOutErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    AdminTelegramControllerLogOutResponses,
    AdminTelegramControllerLogOutErrors,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await zAdminTelegramControllerLogOutResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/session',
    ...options,
  });

export const adminTelegramControllerRefreshChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerRefreshChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerRefreshChatsResponses,
  AdminTelegramControllerRefreshChatsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    AdminTelegramControllerRefreshChatsResponses,
    AdminTelegramControllerRefreshChatsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerRefreshChatsResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/chats/refresh',
    ...options,
  });

export const adminTelegramControllerListChats = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerListChatsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerListChatsResponses,
  AdminTelegramControllerListChatsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerListChatsResponses,
    AdminTelegramControllerListChatsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerListChatsResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/chats',
    ...options,
  });

export const adminTelegramControllerScanOptions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminTelegramControllerScanOptionsData, ThrowOnError>,
): RequestResult<
  AdminTelegramControllerScanOptionsResponses,
  AdminTelegramControllerScanOptionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AdminTelegramControllerScanOptionsResponses,
    AdminTelegramControllerScanOptionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zAdminTelegramControllerScanOptionsResponse.parseAsync(data),
    url: '/api/admin/v1/telegram/chats/scan-options',
    ...options,
  });
