// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type Object = {
  [key: string]: unknown;
};

export type TaxonomyReferenceResponseDto = {
  id: string;
  name: string;
};

export type LinkSourceResponseDto = {
  id: string;
  chatId: string;
  chatName: string;
  messageId: number;
  messagePreview: string;
  messageText?: string;
  messageUrl?: {
    [key: string]: unknown;
  } | null;
  rawUrl: string;
  senderName?: {
    [key: string]: unknown;
  } | null;
  capturedAt: string;
};

export type LinkResponseDto = {
  id: string;
  title: string;
  url: string;
  domain: string;
  environment: 'production' | 'test' | 'development' | 'unknown';
  status: 'pending' | 'organized';
  project: TaxonomyReferenceResponseDto | null;
  category: TaxonomyReferenceResponseDto | null;
  tags: Array<TaxonomyReferenceResponseDto>;
  purpose: {
    [key: string]: unknown;
  } | null;
  isFavorite: boolean;
  sourceCount: number;
  latestSource: LinkSourceResponseDto | null;
  sources?: Array<LinkSourceResponseDto>;
  firstDiscoveredAt: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: {
    [key: string]: unknown;
  } | null;
};

export type PaginationMetaResponseDto = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
};

export type PaginatedLinksResponseDto = {
  items: Array<LinkResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type BatchLinkPatchDto = {
  title?: string;
  url?: string;
  purpose?: {
    [key: string]: unknown;
  } | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: {
    [key: string]: unknown;
  } | null;
  categoryId?: {
    [key: string]: unknown;
  } | null;
  tagIds?: Array<Array<unknown>>;
  isFavorite?: boolean;
  addTagIds?: Array<Array<unknown>>;
};

export type BatchUpdateLinksDto = {
  ids: Array<Array<unknown>>;
  patch: BatchLinkPatchDto;
};

export type UpdateLinkDto = {
  title?: string;
  url?: string;
  purpose?: {
    [key: string]: unknown;
  } | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: {
    [key: string]: unknown;
  } | null;
  categoryId?: {
    [key: string]: unknown;
  } | null;
  tagIds?: Array<Array<unknown>>;
  isFavorite?: boolean;
};

export type CreateSyncJobDto = {
  chatIds?: Array<Array<unknown>>;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom?: string;
  rangeTo?: string;
  defaultProjectId?: string;
  defaultCategoryId?: string;
  defaultTagIds?: Array<Array<unknown>>;
};

export type TaxonomyNameDto = {
  name: string;
};

export type SendCodeDto = {
  phoneNumber: string;
};

export type VerifyCodeDto = {
  challengeId: string;
};

export type VerifyPasswordDto = {
  challengeId: string;
};

export type UpdateChatDto = {
  isEnabled: boolean;
};

export type ObjectWritable = {
  [key: string]: unknown;
};

export type VerifyCodeDtoWritable = {
  challengeId: string;
  code: string;
};

export type VerifyPasswordDtoWritable = {
  challengeId: string;
  password: string;
};

export type AdminLinksControllerOverviewData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/overview';
};

export type AdminLinksControllerOverviewResponses = {
  /**
   * Admin 工作台概览。
   */
  200: unknown;
};

export type AdminLinksControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: ObjectWritable;
    pageSize?: ObjectWritable;
    q?: string;
    view?: 'all' | 'recent' | 'favorites' | 'pending';
    /**
     * UUID 或 unassigned
     */
    projectId?: string;
    categoryId?: string;
    environment?: 'production' | 'test' | 'development' | 'unknown';
    status?: 'pending' | 'organized';
    sort?: 'newest' | 'oldest' | 'title';
    sourceChatId?: string;
    tagIds?: Array<string>;
    includeArchived?: boolean;
  };
  url: '/api/admin/v1/links';
};

export type AdminLinksControllerListResponses = {
  200: PaginatedLinksResponseDto;
};

export type AdminLinksControllerListResponse =
  AdminLinksControllerListResponses[keyof AdminLinksControllerListResponses];

export type AdminLinksControllerBatchData = {
  body: BatchUpdateLinksDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/links/batch';
};

export type AdminLinksControllerBatchResponses = {
  /**
   * 批量整理结果。
   */
  200: unknown;
};

export type AdminLinksControllerArchiveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerArchiveResponses = {
  /**
   * 链接已归档。
   */
  204: void;
};

export type AdminLinksControllerArchiveResponse =
  AdminLinksControllerArchiveResponses[keyof AdminLinksControllerArchiveResponses];

export type AdminLinksControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerFindOneResponses = {
  200: LinkResponseDto;
};

export type AdminLinksControllerFindOneResponse =
  AdminLinksControllerFindOneResponses[keyof AdminLinksControllerFindOneResponses];

export type AdminLinksControllerUpdateData = {
  body: UpdateLinkDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerUpdateResponses = {
  200: LinkResponseDto;
};

export type AdminLinksControllerUpdateResponse =
  AdminLinksControllerUpdateResponses[keyof AdminLinksControllerUpdateResponses];

export type AdminLinksControllerRestoreData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}/restore';
};

export type AdminLinksControllerRestoreResponses = {
  200: LinkResponseDto;
};

export type AdminLinksControllerRestoreResponse =
  AdminLinksControllerRestoreResponses[keyof AdminLinksControllerRestoreResponses];

export type AdminSyncControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: ObjectWritable;
    pageSize?: ObjectWritable;
  };
  url: '/api/admin/v1/sync-jobs';
};

export type AdminSyncControllerListResponses = {
  /**
   * 同步任务列表。
   */
  200: unknown;
};

export type AdminSyncControllerCreateData = {
  body: CreateSyncJobDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/sync-jobs';
};

export type AdminSyncControllerCreateResponses = {
  /**
   * 同步任务已进入后台执行。
   */
  202: unknown;
};

export type AdminSyncControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/sync-jobs/{id}';
};

export type AdminSyncControllerFindOneResponses = {
  /**
   * 同步任务详情与聊天级进度。
   */
  200: unknown;
};

export type AdminTaxonomyControllerListData = {
  body?: never;
  path: {
    kind: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}';
};

export type AdminTaxonomyControllerListResponses = {
  /**
   * 基础资料列表及引用数。
   */
  200: unknown;
};

export type AdminTaxonomyControllerCreateData = {
  body: TaxonomyNameDto;
  path: {
    kind: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}';
};

export type AdminTaxonomyControllerCreateResponses = {
  /**
   * 新增基础资料。
   */
  200: unknown;
};

export type AdminTaxonomyControllerRemoveData = {
  body?: never;
  path: {
    kind: string;
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}/{id}';
};

export type AdminTaxonomyControllerRemoveResponses = {
  /**
   * 删除未被引用的基础资料。
   */
  204: void;
};

export type AdminTaxonomyControllerRemoveResponse =
  AdminTaxonomyControllerRemoveResponses[keyof AdminTaxonomyControllerRemoveResponses];

export type AdminTaxonomyControllerRenameData = {
  body: TaxonomyNameDto;
  path: {
    kind: string;
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}/{id}';
};

export type AdminTaxonomyControllerRenameResponses = {
  /**
   * 重命名基础资料。
   */
  200: unknown;
};

export type AdminTelegramControllerAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/account';
};

export type AdminTelegramControllerAccountResponses = {
  /**
   * Telegram 配置与授权状态。
   */
  200: unknown;
};

export type AdminTelegramControllerSendCodeData = {
  body: SendCodeDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/code';
};

export type AdminTelegramControllerSendCodeResponses = {
  /**
   * 验证码已请求。
   */
  202: unknown;
};

export type AdminTelegramControllerVerifyCodeData = {
  body: VerifyCodeDtoWritable;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/code/verify';
};

export type AdminTelegramControllerVerifyCodeResponses = {
  /**
   * 验证码验证结果。
   */
  200: unknown;
};

export type AdminTelegramControllerVerifyPasswordData = {
  body: VerifyPasswordDtoWritable;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/password/verify';
};

export type AdminTelegramControllerVerifyPasswordResponses = {
  /**
   * 2FA 验证结果。
   */
  200: unknown;
};

export type AdminTelegramControllerLogOutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/session';
};

export type AdminTelegramControllerLogOutResponses = {
  /**
   * 本地 Telegram 会话已清除。
   */
  204: void;
};

export type AdminTelegramControllerLogOutResponse =
  AdminTelegramControllerLogOutResponses[keyof AdminTelegramControllerLogOutResponses];

export type AdminTelegramControllerRefreshChatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/chats/refresh';
};

export type AdminTelegramControllerRefreshChatsResponses = {
  /**
   * Telegram 聊天列表已刷新。
   */
  200: unknown;
};

export type AdminTelegramControllerListChatsData = {
  body?: never;
  path?: never;
  query?: {
    page?: ObjectWritable;
    pageSize?: ObjectWritable;
    query?: string;
    type?: 'saved' | 'private' | 'group' | 'channel';
  };
  url: '/api/admin/v1/telegram/chats';
};

export type AdminTelegramControllerListChatsResponses = {
  /**
   * Telegram 聊天列表。
   */
  200: unknown;
};

export type AdminTelegramControllerUpdateChatData = {
  body: UpdateChatDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/telegram/chats/{id}';
};

export type AdminTelegramControllerUpdateChatResponses = {
  /**
   * 聊天同步开关已更新。
   */
  200: unknown;
};
