// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type AdminSessionResponseDto = {
  authenticated: boolean;
  username?: string;
};

export type AdminLoginDto = {
  username: string;
  password: string;
};

export type ApiErrorResponseDto = {
  statusCode: number;
  code: string;
  message: string;
  details?: Array<string>;
  path: string;
  timestamp: string;
};

export type OverviewCountResponseDto = {
  count: number;
  id: string;
  name: string;
};

export type WebOverviewCountsResponseDto = {
  recent: number;
  total: number;
};

export type WebLatestSyncResponseDto = {
  finishedAt: string | null;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
};

export type WebOverviewResponseDto = {
  categories: Array<OverviewCountResponseDto>;
  counts: WebOverviewCountsResponseDto;
  latestSync: WebLatestSyncResponseDto | null;
  tags: Array<OverviewCountResponseDto>;
};

export type TaxonomyReferenceResponseDto = {
  id: string;
  name: string;
};

export type LinkSourceResponseDto = {
  id: string;
  chatId: string;
  chatName: string;
  messageId: number;
  messagePreview: string;
  messageText?: string;
  messageUrl?: string | null;
  rawUrl: string;
  senderName?: string | null;
  capturedAt: string;
};

export type LinkResponseDto = {
  id: string;
  title: string;
  url: string;
  domain: string;
  status: 'pending' | 'organized';
  category: TaxonomyReferenceResponseDto | null;
  tags: Array<TaxonomyReferenceResponseDto>;
  purpose: string | null;
  sourceCount: number;
  latestSource: LinkSourceResponseDto | null;
  sources?: Array<LinkSourceResponseDto>;
  firstDiscoveredAt: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
};

export type PaginationMetaResponseDto = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
};

export type PaginatedLinksResponseDto = {
  items: Array<LinkResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type LatestSyncSummaryResponseDto = {
  id: string;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
  finishedAt: string | null;
  createdAt: string;
};

export type AdminOverviewResponseDto = {
  archived: number;
  latestSync: LatestSyncSummaryResponseDto | null;
  pending: number;
  todayAdded: number;
  total: number;
};

export type BatchLinkPatchDto = {
  title?: string;
  url?: string;
  purpose?: string | null;
  status?: 'pending' | 'organized';
  categoryId?: string | null;
  tagIds?: Array<string>;
  addTagIds?: Array<string>;
};

export type BatchUpdateLinksDto = {
  ids: Array<string>;
  patch: BatchLinkPatchDto;
};

export type BatchSkippedLinkResponseDto = {
  id: string;
  code: string;
  message: string;
};

export type BatchUpdateLinksResponseDto = {
  updatedIds: Array<string>;
  skipped: Array<BatchSkippedLinkResponseDto>;
};

export type BatchArchiveLinksDto = {
  ids: Array<string>;
};

export type AdminLinkResponseDto = {
  id: string;
  title: string;
  url: string;
  domain: string;
  status: 'pending' | 'organized';
  category: TaxonomyReferenceResponseDto | null;
  tags: Array<TaxonomyReferenceResponseDto>;
  purpose: string | null;
  sourceCount: number;
  latestSource: LinkSourceResponseDto | null;
  sources?: Array<LinkSourceResponseDto>;
  firstDiscoveredAt: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
};

export type UpdateLinkDto = {
  title?: string;
  url?: string;
  purpose?: string | null;
  status?: 'pending' | 'organized';
  categoryId?: string | null;
  tagIds?: Array<string>;
};

export type CreateSyncJobDto = {
  chatIds: Array<string>;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom?: string;
  rangeTo?: string;
  defaultCategoryId?: string;
  defaultTagIds?: Array<string>;
};

export type SyncJobChatResponseDto = {
  id: string;
  chatId: string;
  chatTitle: string;
  status: 'pending' | 'running' | 'succeeded' | 'failed';
  messageCount: number;
  foundCount: number;
  newCount: number;
  duplicateCount: number;
  maxProcessedMessageId: number | null;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
};

export type SyncJobResponseDto = {
  id: string;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
  stage:
    | 'connecting'
    | 'reading'
    | 'extracting'
    | 'deduplicating'
    | 'saving'
    | null;
  progress: number;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom: string | null;
  rangeTo: string | null;
  defaultCategoryId: string | null;
  defaultTagIds: Array<string>;
  messageCount: number;
  foundCount: number;
  newCount: number;
  duplicateCount: number;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  chats: Array<SyncJobChatResponseDto>;
};

export type PaginatedSyncJobsResponseDto = {
  items: Array<SyncJobResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type TaxonomyItemResponseDto = {
  id: string;
  name: string;
  referenceCount: number;
};

export type TaxonomyNameDto = {
  name: string;
};

export type TelegramAccountProfileResponseDto = {
  displayName: string | null;
  phoneNumber: string | null;
  telegramUserId: string | null;
  username: string | null;
};

export type TelegramAccountResponseDto = {
  configured: boolean;
  status: 'authorized' | 'unauthorized';
  account: TelegramAccountProfileResponseDto | null;
};

export type SendCodeDto = {
  phoneNumber: string;
};

export type SendCodeResponseDto = {
  challengeId: string;
  delivery: 'app' | 'sms';
  expiresAt: string;
};

export type VerifyCodeDto = {
  challengeId: string;
};

export type TelegramAuthResultResponseDto = {
  status: 'authorized' | 'passwordRequired';
};

export type VerifyPasswordDto = {
  challengeId: string;
};

export type RefreshChatsResponseDto = {
  count: number;
  refreshedAt: string;
};

export type TelegramChatResponseDto = {
  id: string;
  telegramPeerId: string;
  type: 'saved' | 'private' | 'group' | 'channel';
  title: string;
  username: string | null;
  isAvailable: boolean;
  lastSyncedMessageId: number | null;
  lastSyncedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PaginatedTelegramChatsResponseDto = {
  items: Array<TelegramChatResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type TelegramChatScanOptionResponseDto = {
  id: string;
  telegramPeerId: string;
  type: 'saved' | 'private' | 'group' | 'channel';
  title: string;
  username: string | null;
};

export type TelegramChatScanOptionsResponseDto = {
  items: Array<TelegramChatScanOptionResponseDto>;
};

export type VerifyCodeDtoWritable = {
  challengeId: string;
  code: string;
};

export type VerifyPasswordDtoWritable = {
  challengeId: string;
  password: string;
};

export type AdminAuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/auth/session';
};

export type AdminAuthControllerLogoutResponses = {
  /**
   * 管理端会话已清除。
   */
  204: void;
};

export type AdminAuthControllerLogoutResponse =
  AdminAuthControllerLogoutResponses[keyof AdminAuthControllerLogoutResponses];

export type AdminAuthControllerSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/auth/session';
};

export type AdminAuthControllerSessionResponses = {
  200: AdminSessionResponseDto;
};

export type AdminAuthControllerSessionResponse =
  AdminAuthControllerSessionResponses[keyof AdminAuthControllerSessionResponses];

export type AdminAuthControllerLoginData = {
  body: AdminLoginDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/auth/session';
};

export type AdminAuthControllerLoginErrors = {
  401: ApiErrorResponseDto;
  429: ApiErrorResponseDto;
};

export type AdminAuthControllerLoginError =
  AdminAuthControllerLoginErrors[keyof AdminAuthControllerLoginErrors];

export type AdminAuthControllerLoginResponses = {
  200: AdminSessionResponseDto;
};

export type AdminAuthControllerLoginResponse =
  AdminAuthControllerLoginResponses[keyof AdminAuthControllerLoginResponses];

export type AdminLinksControllerOverviewData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/overview';
};

export type AdminLinksControllerOverviewErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerOverviewError =
  AdminLinksControllerOverviewErrors[keyof AdminLinksControllerOverviewErrors];

export type AdminLinksControllerOverviewResponses = {
  200: AdminOverviewResponseDto;
};

export type AdminLinksControllerOverviewResponse =
  AdminLinksControllerOverviewResponses[keyof AdminLinksControllerOverviewResponses];

export type AdminLinksControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    q?: string;
    view?: 'all' | 'recent' | 'pending';
    categoryId?: string;
    status?: 'pending' | 'organized';
    sort?: 'newest' | 'oldest' | 'title';
    sourceChatId?: string;
    tagIds?: Array<string>;
    includeArchived?: boolean;
  };
  url: '/api/admin/v1/links';
};

export type AdminLinksControllerListErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerListError =
  AdminLinksControllerListErrors[keyof AdminLinksControllerListErrors];

export type AdminLinksControllerListResponses = {
  200: PaginatedLinksResponseDto;
};

export type AdminLinksControllerListResponse =
  AdminLinksControllerListResponses[keyof AdminLinksControllerListResponses];

export type AdminLinksControllerBatchData = {
  body: BatchUpdateLinksDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/links/batch';
};

export type AdminLinksControllerBatchErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerBatchError =
  AdminLinksControllerBatchErrors[keyof AdminLinksControllerBatchErrors];

export type AdminLinksControllerBatchResponses = {
  200: BatchUpdateLinksResponseDto;
};

export type AdminLinksControllerBatchResponse =
  AdminLinksControllerBatchResponses[keyof AdminLinksControllerBatchResponses];

export type AdminLinksControllerBatchArchiveData = {
  body: BatchArchiveLinksDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/links/batch/archive';
};

export type AdminLinksControllerBatchArchiveErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerBatchArchiveError =
  AdminLinksControllerBatchArchiveErrors[keyof AdminLinksControllerBatchArchiveErrors];

export type AdminLinksControllerBatchArchiveResponses = {
  200: BatchUpdateLinksResponseDto;
};

export type AdminLinksControllerBatchArchiveResponse =
  AdminLinksControllerBatchArchiveResponses[keyof AdminLinksControllerBatchArchiveResponses];

export type AdminLinksControllerArchiveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerArchiveErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerArchiveError =
  AdminLinksControllerArchiveErrors[keyof AdminLinksControllerArchiveErrors];

export type AdminLinksControllerArchiveResponses = {
  /**
   * 链接已归档。
   */
  204: void;
};

export type AdminLinksControllerArchiveResponse =
  AdminLinksControllerArchiveResponses[keyof AdminLinksControllerArchiveResponses];

export type AdminLinksControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerFindOneErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerFindOneError =
  AdminLinksControllerFindOneErrors[keyof AdminLinksControllerFindOneErrors];

export type AdminLinksControllerFindOneResponses = {
  200: AdminLinkResponseDto;
};

export type AdminLinksControllerFindOneResponse =
  AdminLinksControllerFindOneResponses[keyof AdminLinksControllerFindOneResponses];

export type AdminLinksControllerUpdateData = {
  body: UpdateLinkDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}';
};

export type AdminLinksControllerUpdateErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerUpdateError =
  AdminLinksControllerUpdateErrors[keyof AdminLinksControllerUpdateErrors];

export type AdminLinksControllerUpdateResponses = {
  200: AdminLinkResponseDto;
};

export type AdminLinksControllerUpdateResponse =
  AdminLinksControllerUpdateResponses[keyof AdminLinksControllerUpdateResponses];

export type AdminLinksControllerRestoreData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/links/{id}/restore';
};

export type AdminLinksControllerRestoreErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminLinksControllerRestoreError =
  AdminLinksControllerRestoreErrors[keyof AdminLinksControllerRestoreErrors];

export type AdminLinksControllerRestoreResponses = {
  200: AdminLinkResponseDto;
};

export type AdminLinksControllerRestoreResponse =
  AdminLinksControllerRestoreResponses[keyof AdminLinksControllerRestoreResponses];

export type AdminSyncControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
  };
  url: '/api/admin/v1/sync-jobs';
};

export type AdminSyncControllerListErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminSyncControllerListError =
  AdminSyncControllerListErrors[keyof AdminSyncControllerListErrors];

export type AdminSyncControllerListResponses = {
  200: PaginatedSyncJobsResponseDto;
};

export type AdminSyncControllerListResponse =
  AdminSyncControllerListResponses[keyof AdminSyncControllerListResponses];

export type AdminSyncControllerCreateData = {
  body: CreateSyncJobDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/sync-jobs';
};

export type AdminSyncControllerCreateErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminSyncControllerCreateError =
  AdminSyncControllerCreateErrors[keyof AdminSyncControllerCreateErrors];

export type AdminSyncControllerCreateResponses = {
  202: SyncJobResponseDto;
};

export type AdminSyncControllerCreateResponse =
  AdminSyncControllerCreateResponses[keyof AdminSyncControllerCreateResponses];

export type AdminSyncControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/sync-jobs/{id}';
};

export type AdminSyncControllerFindOneErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminSyncControllerFindOneError =
  AdminSyncControllerFindOneErrors[keyof AdminSyncControllerFindOneErrors];

export type AdminSyncControllerFindOneResponses = {
  200: SyncJobResponseDto;
};

export type AdminSyncControllerFindOneResponse =
  AdminSyncControllerFindOneResponses[keyof AdminSyncControllerFindOneResponses];

export type AdminTaxonomyControllerListData = {
  body?: never;
  path: {
    kind: 'categories' | 'tags';
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}';
};

export type AdminTaxonomyControllerListErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminTaxonomyControllerListError =
  AdminTaxonomyControllerListErrors[keyof AdminTaxonomyControllerListErrors];

export type AdminTaxonomyControllerListResponses = {
  200: Array<TaxonomyItemResponseDto>;
};

export type AdminTaxonomyControllerListResponse =
  AdminTaxonomyControllerListResponses[keyof AdminTaxonomyControllerListResponses];

export type AdminTaxonomyControllerCreateData = {
  body: TaxonomyNameDto;
  path: {
    kind: 'categories' | 'tags';
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}';
};

export type AdminTaxonomyControllerCreateErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminTaxonomyControllerCreateError =
  AdminTaxonomyControllerCreateErrors[keyof AdminTaxonomyControllerCreateErrors];

export type AdminTaxonomyControllerCreateResponses = {
  201: TaxonomyItemResponseDto;
};

export type AdminTaxonomyControllerCreateResponse =
  AdminTaxonomyControllerCreateResponses[keyof AdminTaxonomyControllerCreateResponses];

export type AdminTaxonomyControllerRemoveData = {
  body?: never;
  path: {
    kind: 'categories' | 'tags';
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}/{id}';
};

export type AdminTaxonomyControllerRemoveErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminTaxonomyControllerRemoveError =
  AdminTaxonomyControllerRemoveErrors[keyof AdminTaxonomyControllerRemoveErrors];

export type AdminTaxonomyControllerRemoveResponses = {
  /**
   * 删除未被引用的基础资料。
   */
  204: void;
};

export type AdminTaxonomyControllerRemoveResponse =
  AdminTaxonomyControllerRemoveResponses[keyof AdminTaxonomyControllerRemoveResponses];

export type AdminTaxonomyControllerRenameData = {
  body: TaxonomyNameDto;
  path: {
    kind: 'categories' | 'tags';
    id: string;
  };
  query?: never;
  url: '/api/admin/v1/taxonomy/{kind}/{id}';
};

export type AdminTaxonomyControllerRenameErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type AdminTaxonomyControllerRenameError =
  AdminTaxonomyControllerRenameErrors[keyof AdminTaxonomyControllerRenameErrors];

export type AdminTaxonomyControllerRenameResponses = {
  200: TaxonomyItemResponseDto;
};

export type AdminTaxonomyControllerRenameResponse =
  AdminTaxonomyControllerRenameResponses[keyof AdminTaxonomyControllerRenameResponses];

export type AdminTelegramControllerAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/account';
};

export type AdminTelegramControllerAccountErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerAccountError =
  AdminTelegramControllerAccountErrors[keyof AdminTelegramControllerAccountErrors];

export type AdminTelegramControllerAccountResponses = {
  200: TelegramAccountResponseDto;
};

export type AdminTelegramControllerAccountResponse =
  AdminTelegramControllerAccountResponses[keyof AdminTelegramControllerAccountResponses];

export type AdminTelegramControllerSendCodeData = {
  body: SendCodeDto;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/code';
};

export type AdminTelegramControllerSendCodeErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerSendCodeError =
  AdminTelegramControllerSendCodeErrors[keyof AdminTelegramControllerSendCodeErrors];

export type AdminTelegramControllerSendCodeResponses = {
  202: SendCodeResponseDto;
};

export type AdminTelegramControllerSendCodeResponse =
  AdminTelegramControllerSendCodeResponses[keyof AdminTelegramControllerSendCodeResponses];

export type AdminTelegramControllerVerifyCodeData = {
  body: VerifyCodeDtoWritable;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/code/verify';
};

export type AdminTelegramControllerVerifyCodeErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerVerifyCodeError =
  AdminTelegramControllerVerifyCodeErrors[keyof AdminTelegramControllerVerifyCodeErrors];

export type AdminTelegramControllerVerifyCodeResponses = {
  200: TelegramAuthResultResponseDto;
};

export type AdminTelegramControllerVerifyCodeResponse =
  AdminTelegramControllerVerifyCodeResponses[keyof AdminTelegramControllerVerifyCodeResponses];

export type AdminTelegramControllerVerifyPasswordData = {
  body: VerifyPasswordDtoWritable;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/auth/password/verify';
};

export type AdminTelegramControllerVerifyPasswordErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerVerifyPasswordError =
  AdminTelegramControllerVerifyPasswordErrors[keyof AdminTelegramControllerVerifyPasswordErrors];

export type AdminTelegramControllerVerifyPasswordResponses = {
  200: TelegramAuthResultResponseDto;
};

export type AdminTelegramControllerVerifyPasswordResponse =
  AdminTelegramControllerVerifyPasswordResponses[keyof AdminTelegramControllerVerifyPasswordResponses];

export type AdminTelegramControllerLogOutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/session';
};

export type AdminTelegramControllerLogOutErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerLogOutError =
  AdminTelegramControllerLogOutErrors[keyof AdminTelegramControllerLogOutErrors];

export type AdminTelegramControllerLogOutResponses = {
  /**
   * 本地 Telegram 会话已清除。
   */
  204: void;
};

export type AdminTelegramControllerLogOutResponse =
  AdminTelegramControllerLogOutResponses[keyof AdminTelegramControllerLogOutResponses];

export type AdminTelegramControllerRefreshChatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/chats/refresh';
};

export type AdminTelegramControllerRefreshChatsErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerRefreshChatsError =
  AdminTelegramControllerRefreshChatsErrors[keyof AdminTelegramControllerRefreshChatsErrors];

export type AdminTelegramControllerRefreshChatsResponses = {
  200: RefreshChatsResponseDto;
};

export type AdminTelegramControllerRefreshChatsResponse =
  AdminTelegramControllerRefreshChatsResponses[keyof AdminTelegramControllerRefreshChatsResponses];

export type AdminTelegramControllerListChatsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    query?: string;
    type?: 'saved' | 'private' | 'group' | 'channel';
  };
  url: '/api/admin/v1/telegram/chats';
};

export type AdminTelegramControllerListChatsErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerListChatsError =
  AdminTelegramControllerListChatsErrors[keyof AdminTelegramControllerListChatsErrors];

export type AdminTelegramControllerListChatsResponses = {
  200: PaginatedTelegramChatsResponseDto;
};

export type AdminTelegramControllerListChatsResponse =
  AdminTelegramControllerListChatsResponses[keyof AdminTelegramControllerListChatsResponses];

export type AdminTelegramControllerScanOptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/v1/telegram/chats/scan-options';
};

export type AdminTelegramControllerScanOptionsErrors = {
  400: ApiErrorResponseDto;
  401: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  410: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
  503: ApiErrorResponseDto;
};

export type AdminTelegramControllerScanOptionsError =
  AdminTelegramControllerScanOptionsErrors[keyof AdminTelegramControllerScanOptionsErrors];

export type AdminTelegramControllerScanOptionsResponses = {
  200: TelegramChatScanOptionsResponseDto;
};

export type AdminTelegramControllerScanOptionsResponse =
  AdminTelegramControllerScanOptionsResponses[keyof AdminTelegramControllerScanOptionsResponses];
