// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zObject = z.record(z.string(), z.unknown());

export const zTaxonomyReferenceResponseDto = z.object({
  id: z.uuid(),
  name: z.string(),
});

export const zLinkSourceResponseDto = z.object({
  id: z.uuid(),
  chatId: z.uuid(),
  chatName: z.string(),
  messageId: z.number(),
  messagePreview: z.string(),
  messageText: z.string().optional(),
  messageUrl: z.record(z.string(), z.unknown()).nullish(),
  rawUrl: z.string(),
  senderName: z.record(z.string(), z.unknown()).nullish(),
  capturedAt: z.iso.datetime(),
});

export const zLinkResponseDto = z.object({
  id: z.uuid(),
  title: z.string(),
  url: z.string(),
  domain: z.string(),
  environment: z.enum(['production', 'test', 'development', 'unknown']),
  status: z.enum(['pending', 'organized']),
  project: zTaxonomyReferenceResponseDto.nullable(),
  category: zTaxonomyReferenceResponseDto.nullable(),
  tags: z.array(zTaxonomyReferenceResponseDto),
  purpose: z.record(z.string(), z.unknown()).nullable(),
  isFavorite: z.boolean(),
  sourceCount: z.number(),
  latestSource: zLinkSourceResponseDto.nullable(),
  sources: z.array(zLinkSourceResponseDto).optional(),
  firstDiscoveredAt: z.iso.datetime(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  archivedAt: z.record(z.string(), z.unknown()).nullable(),
});

export const zPaginationMetaResponseDto = z.object({
  page: z.number(),
  pageSize: z.number(),
  total: z.number(),
  totalPages: z.number(),
});

export const zPaginatedLinksResponseDto = z.object({
  items: z.array(zLinkResponseDto),
  pagination: zPaginationMetaResponseDto,
});

export const zBatchLinkPatchDto = z.object({
  title: z.string().optional(),
  url: z.string().optional(),
  purpose: z.record(z.string(), z.unknown()).nullish(),
  environment: z
    .enum(['production', 'test', 'development', 'unknown'])
    .optional(),
  status: z.enum(['pending', 'organized']).optional(),
  projectId: z.record(z.string(), z.unknown()).nullish(),
  categoryId: z.record(z.string(), z.unknown()).nullish(),
  tagIds: z.array(z.array(z.unknown())).optional(),
  isFavorite: z.boolean().optional(),
  addTagIds: z.array(z.array(z.unknown())).optional(),
});

export const zBatchUpdateLinksDto = z.object({
  ids: z.array(z.array(z.unknown())),
  patch: zBatchLinkPatchDto,
});

export const zUpdateLinkDto = z.object({
  title: z.string().optional(),
  url: z.string().optional(),
  purpose: z.record(z.string(), z.unknown()).nullish(),
  environment: z
    .enum(['production', 'test', 'development', 'unknown'])
    .optional(),
  status: z.enum(['pending', 'organized']).optional(),
  projectId: z.record(z.string(), z.unknown()).nullish(),
  categoryId: z.record(z.string(), z.unknown()).nullish(),
  tagIds: z.array(z.array(z.unknown())).optional(),
  isFavorite: z.boolean().optional(),
});

export const zCreateSyncJobDto = z.object({
  chatIds: z.array(z.array(z.unknown())).optional(),
  rangeMode: z.enum(['sinceLast', 'last7Days', 'custom', 'allHistory']),
  rangeFrom: z.iso.datetime().optional(),
  rangeTo: z.iso.datetime().optional(),
  defaultProjectId: z.uuid().optional(),
  defaultCategoryId: z.uuid().optional(),
  defaultTagIds: z.array(z.array(z.unknown())).optional(),
});

export const zTaxonomyNameDto = z.object({
  name: z.string(),
});

export const zSendCodeDto = z.object({
  phoneNumber: z.string(),
});

export const zVerifyCodeDto = z.object({
  challengeId: z.uuid(),
});

export const zVerifyPasswordDto = z.object({
  challengeId: z.uuid(),
});

export const zUpdateChatDto = z.object({
  isEnabled: z.boolean(),
});

export const zObjectWritable = z.record(z.string(), z.unknown());

export const zVerifyCodeDtoWritable = z.object({
  challengeId: z.uuid(),
  code: z.string(),
});

export const zVerifyPasswordDtoWritable = z.object({
  challengeId: z.uuid(),
  password: z.string(),
});

export const zAdminLinksControllerListQuery = z.object({
  page: zObjectWritable.optional(),
  pageSize: zObjectWritable.optional(),
  q: z.string().optional(),
  view: z.enum(['all', 'recent', 'favorites', 'pending']).optional(),
  projectId: z.string().optional(),
  categoryId: z.uuid().optional(),
  environment: z
    .enum(['production', 'test', 'development', 'unknown'])
    .optional(),
  status: z.enum(['pending', 'organized']).optional(),
  sort: z.enum(['newest', 'oldest', 'title']).optional(),
  sourceChatId: z.uuid().optional(),
  tagIds: z.array(z.string()).optional(),
  includeArchived: z.boolean().optional().default(false),
});

export const zAdminLinksControllerListResponse = zPaginatedLinksResponseDto;

export const zAdminLinksControllerBatchBody = zBatchUpdateLinksDto;

export const zAdminLinksControllerArchivePath = z.object({
  id: z.string(),
});

/**
 * 链接已归档。
 */
export const zAdminLinksControllerArchiveResponse = z.void();

export const zAdminLinksControllerFindOnePath = z.object({
  id: z.string(),
});

export const zAdminLinksControllerFindOneResponse = zLinkResponseDto;

export const zAdminLinksControllerUpdateBody = zUpdateLinkDto;

export const zAdminLinksControllerUpdatePath = z.object({
  id: z.string(),
});

export const zAdminLinksControllerUpdateResponse = zLinkResponseDto;

export const zAdminLinksControllerRestorePath = z.object({
  id: z.string(),
});

export const zAdminLinksControllerRestoreResponse = zLinkResponseDto;

export const zAdminSyncControllerListQuery = z.object({
  page: zObjectWritable.optional(),
  pageSize: zObjectWritable.optional(),
});

export const zAdminSyncControllerCreateBody = zCreateSyncJobDto;

export const zAdminSyncControllerFindOnePath = z.object({
  id: z.string(),
});

export const zAdminTaxonomyControllerListPath = z.object({
  kind: z.string(),
});

export const zAdminTaxonomyControllerCreateBody = zTaxonomyNameDto;

export const zAdminTaxonomyControllerCreatePath = z.object({
  kind: z.string(),
});

export const zAdminTaxonomyControllerRemovePath = z.object({
  kind: z.string(),
  id: z.string(),
});

/**
 * 删除未被引用的基础资料。
 */
export const zAdminTaxonomyControllerRemoveResponse = z.void();

export const zAdminTaxonomyControllerRenameBody = zTaxonomyNameDto;

export const zAdminTaxonomyControllerRenamePath = z.object({
  kind: z.string(),
  id: z.string(),
});

export const zAdminTelegramControllerSendCodeBody = zSendCodeDto;

export const zAdminTelegramControllerVerifyCodeBody = zVerifyCodeDtoWritable;

export const zAdminTelegramControllerVerifyPasswordBody =
  zVerifyPasswordDtoWritable;

/**
 * 本地 Telegram 会话已清除。
 */
export const zAdminTelegramControllerLogOutResponse = z.void();

export const zAdminTelegramControllerListChatsQuery = z.object({
  page: zObjectWritable.optional(),
  pageSize: zObjectWritable.optional(),
  query: z.string().optional(),
  type: z.enum(['saved', 'private', 'group', 'channel']).optional(),
});

export const zAdminTelegramControllerUpdateChatBody = zUpdateChatDto;

export const zAdminTelegramControllerUpdateChatPath = z.object({
  id: z.string(),
});
