/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings';
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links';
import { Route as AuthenticatedSyncJobsRouteImport } from './routes/_authenticated/sync-jobs';
import { Route as AuthenticatedTaxonomyRouteImport } from './routes/_authenticated/taxonomy';
import { Route as AuthenticatedTelegramRouteImport } from './routes/_authenticated/telegram';
import { Route as AuthenticatedLinksIndexRouteImport } from './routes/_authenticated/links.index';
import { Route as AuthenticatedLinksPendingRouteImport } from './routes/_authenticated/links.pending';

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSyncJobsRoute = AuthenticatedSyncJobsRouteImport.update({
  id: '/sync-jobs',
  path: '/sync-jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTaxonomyRoute = AuthenticatedTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTelegramRoute = AuthenticatedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedLinksIndexRoute = AuthenticatedLinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any);
const AuthenticatedLinksPendingRoute =
  AuthenticatedLinksPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedLinksRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/login': typeof LoginRoute;
  '/ai-settings': typeof AuthenticatedAiSettingsRoute;
  '/links': typeof AuthenticatedLinksRouteWithChildren;
  '/sync-jobs': typeof AuthenticatedSyncJobsRoute;
  '/taxonomy': typeof AuthenticatedTaxonomyRoute;
  '/telegram': typeof AuthenticatedTelegramRoute;
  '/links/pending': typeof AuthenticatedLinksPendingRoute;
  '/links/': typeof AuthenticatedLinksIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/ai-settings': typeof AuthenticatedAiSettingsRoute;
  '/sync-jobs': typeof AuthenticatedSyncJobsRoute;
  '/taxonomy': typeof AuthenticatedTaxonomyRoute;
  '/telegram': typeof AuthenticatedTelegramRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/links/pending': typeof AuthenticatedLinksPendingRoute;
  '/links': typeof AuthenticatedLinksIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute;
  '/_authenticated/links': typeof AuthenticatedLinksRouteWithChildren;
  '/_authenticated/sync-jobs': typeof AuthenticatedSyncJobsRoute;
  '/_authenticated/taxonomy': typeof AuthenticatedTaxonomyRoute;
  '/_authenticated/telegram': typeof AuthenticatedTelegramRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/links/pending': typeof AuthenticatedLinksPendingRoute;
  '/_authenticated/links/': typeof AuthenticatedLinksIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/ai-settings'
    | '/links'
    | '/sync-jobs'
    | '/taxonomy'
    | '/telegram'
    | '/links/pending'
    | '/links/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/ai-settings'
    | '/sync-jobs'
    | '/taxonomy'
    | '/telegram'
    | '/'
    | '/links/pending'
    | '/links';
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-settings'
    | '/_authenticated/links'
    | '/_authenticated/sync-jobs'
    | '/_authenticated/taxonomy'
    | '/_authenticated/telegram'
    | '/_authenticated/'
    | '/_authenticated/links/pending'
    | '/_authenticated/links/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings';
      path: '/ai-settings';
      fullPath: '/ai-settings';
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/links': {
      id: '/_authenticated/links';
      path: '/links';
      fullPath: '/links';
      preLoaderRoute: typeof AuthenticatedLinksRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/sync-jobs': {
      id: '/_authenticated/sync-jobs';
      path: '/sync-jobs';
      fullPath: '/sync-jobs';
      preLoaderRoute: typeof AuthenticatedSyncJobsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/taxonomy': {
      id: '/_authenticated/taxonomy';
      path: '/taxonomy';
      fullPath: '/taxonomy';
      preLoaderRoute: typeof AuthenticatedTaxonomyRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/telegram': {
      id: '/_authenticated/telegram';
      path: '/telegram';
      fullPath: '/telegram';
      preLoaderRoute: typeof AuthenticatedTelegramRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/links/': {
      id: '/_authenticated/links/';
      path: '/';
      fullPath: '/links/';
      preLoaderRoute: typeof AuthenticatedLinksIndexRouteImport;
      parentRoute: typeof AuthenticatedLinksRoute;
    };
    '/_authenticated/links/pending': {
      id: '/_authenticated/links/pending';
      path: '/pending';
      fullPath: '/links/pending';
      preLoaderRoute: typeof AuthenticatedLinksPendingRouteImport;
      parentRoute: typeof AuthenticatedLinksRoute;
    };
  }
}

interface AuthenticatedLinksRouteChildren {
  AuthenticatedLinksPendingRoute: typeof AuthenticatedLinksPendingRoute;
  AuthenticatedLinksIndexRoute: typeof AuthenticatedLinksIndexRoute;
}

const AuthenticatedLinksRouteChildren: AuthenticatedLinksRouteChildren = {
  AuthenticatedLinksPendingRoute: AuthenticatedLinksPendingRoute,
  AuthenticatedLinksIndexRoute: AuthenticatedLinksIndexRoute,
};

const AuthenticatedLinksRouteWithChildren =
  AuthenticatedLinksRoute._addFileChildren(AuthenticatedLinksRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute;
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRouteWithChildren;
  AuthenticatedSyncJobsRoute: typeof AuthenticatedSyncJobsRoute;
  AuthenticatedTaxonomyRoute: typeof AuthenticatedTaxonomyRoute;
  AuthenticatedTelegramRoute: typeof AuthenticatedTelegramRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRouteWithChildren,
  AuthenticatedSyncJobsRoute: AuthenticatedSyncJobsRoute,
  AuthenticatedTaxonomyRoute: AuthenticatedTaxonomyRoute,
  AuthenticatedTelegramRoute: AuthenticatedTelegramRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
