// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
} from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  type Options,
  webApiControllerFindOne,
  webApiControllerList,
  webApiControllerOverview,
} from '../sdk.gen';
import type {
  ObjectWritable,
  WebApiControllerFindOneData,
  WebApiControllerFindOneResponse,
  WebApiControllerListData,
  WebApiControllerListResponse,
  WebApiControllerOverviewData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const webApiControllerOverviewQueryKey = (
  options?: Options<WebApiControllerOverviewData>,
) => createQueryKey('webApiControllerOverview', options);

export const webApiControllerOverviewOptions = (
  options?: Options<WebApiControllerOverviewData>,
) =>
  queryOptions<
    unknown,
    AxiosError<DefaultError>,
    unknown,
    ReturnType<typeof webApiControllerOverviewQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await webApiControllerOverview({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: webApiControllerOverviewQueryKey(options),
  });

export const webApiControllerListQueryKey = (
  options?: Options<WebApiControllerListData>,
) => createQueryKey('webApiControllerList', options);

export const webApiControllerListOptions = (
  options?: Options<WebApiControllerListData>,
) =>
  queryOptions<
    WebApiControllerListResponse,
    AxiosError<DefaultError>,
    WebApiControllerListResponse,
    ReturnType<typeof webApiControllerListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await webApiControllerList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: webApiControllerListQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const webApiControllerListInfiniteQueryKey = (
  options?: Options<WebApiControllerListData>,
): QueryKey<Options<WebApiControllerListData>> =>
  createQueryKey('webApiControllerList', options, true);

export const webApiControllerListInfiniteOptions = (
  options?: Options<WebApiControllerListData>,
) =>
  infiniteQueryOptions<
    WebApiControllerListResponse,
    AxiosError<DefaultError>,
    InfiniteData<WebApiControllerListResponse>,
    QueryKey<Options<WebApiControllerListData>>,
    | ObjectWritable
    | Pick<
        QueryKey<Options<WebApiControllerListData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<WebApiControllerListData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await webApiControllerList({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: webApiControllerListInfiniteQueryKey(options),
    },
  );

export const webApiControllerFindOneQueryKey = (
  options: Options<WebApiControllerFindOneData>,
) => createQueryKey('webApiControllerFindOne', options);

export const webApiControllerFindOneOptions = (
  options: Options<WebApiControllerFindOneData>,
) =>
  queryOptions<
    WebApiControllerFindOneResponse,
    AxiosError<DefaultError>,
    WebApiControllerFindOneResponse,
    ReturnType<typeof webApiControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await webApiControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: webApiControllerFindOneQueryKey(options),
  });
