// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  adminAuthControllerLogin,
  adminAuthControllerLogout,
  adminAuthControllerSession,
  adminLinksControllerArchive,
  adminLinksControllerBatch,
  adminLinksControllerBatchArchive,
  adminLinksControllerFindOne,
  adminLinksControllerList,
  adminLinksControllerOverview,
  adminLinksControllerRestore,
  adminLinksControllerUpdate,
  adminSyncControllerCreate,
  adminSyncControllerFindOne,
  adminSyncControllerList,
  adminTaxonomyControllerCreate,
  adminTaxonomyControllerList,
  adminTaxonomyControllerRemove,
  adminTaxonomyControllerRename,
  adminTelegramControllerAccount,
  adminTelegramControllerListChats,
  adminTelegramControllerLogOut,
  adminTelegramControllerRefreshChats,
  adminTelegramControllerScanOptions,
  adminTelegramControllerSendCode,
  adminTelegramControllerVerifyCode,
  adminTelegramControllerVerifyPassword,
  type Options,
} from '../sdk.gen';
import type {
  AdminAuthControllerLoginData,
  AdminAuthControllerLoginError,
  AdminAuthControllerLoginResponse,
  AdminAuthControllerLogoutData,
  AdminAuthControllerLogoutResponse,
  AdminAuthControllerSessionData,
  AdminAuthControllerSessionResponse,
  AdminLinksControllerArchiveData,
  AdminLinksControllerArchiveError,
  AdminLinksControllerArchiveResponse,
  AdminLinksControllerBatchArchiveData,
  AdminLinksControllerBatchArchiveError,
  AdminLinksControllerBatchArchiveResponse,
  AdminLinksControllerBatchData,
  AdminLinksControllerBatchError,
  AdminLinksControllerBatchResponse,
  AdminLinksControllerFindOneData,
  AdminLinksControllerFindOneError,
  AdminLinksControllerFindOneResponse,
  AdminLinksControllerListData,
  AdminLinksControllerListError,
  AdminLinksControllerListResponse,
  AdminLinksControllerOverviewData,
  AdminLinksControllerOverviewError,
  AdminLinksControllerOverviewResponse,
  AdminLinksControllerRestoreData,
  AdminLinksControllerRestoreError,
  AdminLinksControllerRestoreResponse,
  AdminLinksControllerUpdateData,
  AdminLinksControllerUpdateError,
  AdminLinksControllerUpdateResponse,
  AdminSyncControllerCreateData,
  AdminSyncControllerCreateError,
  AdminSyncControllerCreateResponse,
  AdminSyncControllerFindOneData,
  AdminSyncControllerFindOneError,
  AdminSyncControllerFindOneResponse,
  AdminSyncControllerListData,
  AdminSyncControllerListError,
  AdminSyncControllerListResponse,
  AdminTaxonomyControllerCreateData,
  AdminTaxonomyControllerCreateError,
  AdminTaxonomyControllerCreateResponse,
  AdminTaxonomyControllerListData,
  AdminTaxonomyControllerListError,
  AdminTaxonomyControllerListResponse,
  AdminTaxonomyControllerRemoveData,
  AdminTaxonomyControllerRemoveError,
  AdminTaxonomyControllerRemoveResponse,
  AdminTaxonomyControllerRenameData,
  AdminTaxonomyControllerRenameError,
  AdminTaxonomyControllerRenameResponse,
  AdminTelegramControllerAccountData,
  AdminTelegramControllerAccountError,
  AdminTelegramControllerAccountResponse,
  AdminTelegramControllerListChatsData,
  AdminTelegramControllerListChatsError,
  AdminTelegramControllerListChatsResponse,
  AdminTelegramControllerLogOutData,
  AdminTelegramControllerLogOutError,
  AdminTelegramControllerLogOutResponse,
  AdminTelegramControllerRefreshChatsData,
  AdminTelegramControllerRefreshChatsError,
  AdminTelegramControllerRefreshChatsResponse,
  AdminTelegramControllerScanOptionsData,
  AdminTelegramControllerScanOptionsError,
  AdminTelegramControllerScanOptionsResponse,
  AdminTelegramControllerSendCodeData,
  AdminTelegramControllerSendCodeError,
  AdminTelegramControllerSendCodeResponse,
  AdminTelegramControllerVerifyCodeData,
  AdminTelegramControllerVerifyCodeError,
  AdminTelegramControllerVerifyCodeResponse,
  AdminTelegramControllerVerifyPasswordData,
  AdminTelegramControllerVerifyPasswordError,
  AdminTelegramControllerVerifyPasswordResponse,
} from '../types.gen';

export const adminAuthControllerLogoutMutation = (
  options?: Partial<Options<AdminAuthControllerLogoutData>>,
): UseMutationOptions<
  AdminAuthControllerLogoutResponse,
  AxiosError<DefaultError>,
  Options<AdminAuthControllerLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminAuthControllerLogoutResponse,
    AxiosError<DefaultError>,
    Options<AdminAuthControllerLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminAuthControllerLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const adminAuthControllerSessionQueryKey = (
  options?: Options<AdminAuthControllerSessionData>,
) => createQueryKey('adminAuthControllerSession', options);

export const adminAuthControllerSessionOptions = (
  options?: Options<AdminAuthControllerSessionData>,
) =>
  queryOptions<
    AdminAuthControllerSessionResponse,
    AxiosError<DefaultError>,
    AdminAuthControllerSessionResponse,
    ReturnType<typeof adminAuthControllerSessionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminAuthControllerSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminAuthControllerSessionQueryKey(options),
  });

export const adminAuthControllerLoginMutation = (
  options?: Partial<Options<AdminAuthControllerLoginData>>,
): UseMutationOptions<
  AdminAuthControllerLoginResponse,
  AxiosError<AdminAuthControllerLoginError>,
  Options<AdminAuthControllerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminAuthControllerLoginResponse,
    AxiosError<AdminAuthControllerLoginError>,
    Options<AdminAuthControllerLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminAuthControllerLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminLinksControllerOverviewQueryKey = (
  options?: Options<AdminLinksControllerOverviewData>,
) => createQueryKey('adminLinksControllerOverview', options);

export const adminLinksControllerOverviewOptions = (
  options?: Options<AdminLinksControllerOverviewData>,
) =>
  queryOptions<
    AdminLinksControllerOverviewResponse,
    AxiosError<AdminLinksControllerOverviewError>,
    AdminLinksControllerOverviewResponse,
    ReturnType<typeof adminLinksControllerOverviewQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminLinksControllerOverview({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminLinksControllerOverviewQueryKey(options),
  });

export const adminLinksControllerListQueryKey = (
  options?: Options<AdminLinksControllerListData>,
) => createQueryKey('adminLinksControllerList', options);

export const adminLinksControllerListOptions = (
  options?: Options<AdminLinksControllerListData>,
) =>
  queryOptions<
    AdminLinksControllerListResponse,
    AxiosError<AdminLinksControllerListError>,
    AdminLinksControllerListResponse,
    ReturnType<typeof adminLinksControllerListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminLinksControllerList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminLinksControllerListQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const adminLinksControllerListInfiniteQueryKey = (
  options?: Options<AdminLinksControllerListData>,
): QueryKey<Options<AdminLinksControllerListData>> =>
  createQueryKey('adminLinksControllerList', options, true);

export const adminLinksControllerListInfiniteOptions = (
  options?: Options<AdminLinksControllerListData>,
) =>
  infiniteQueryOptions<
    AdminLinksControllerListResponse,
    AxiosError<AdminLinksControllerListError>,
    InfiniteData<AdminLinksControllerListResponse>,
    QueryKey<Options<AdminLinksControllerListData>>,
    | number
    | Pick<
        QueryKey<Options<AdminLinksControllerListData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AdminLinksControllerListData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await adminLinksControllerList({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: adminLinksControllerListInfiniteQueryKey(options),
    },
  );

export const adminLinksControllerBatchMutation = (
  options?: Partial<Options<AdminLinksControllerBatchData>>,
): UseMutationOptions<
  AdminLinksControllerBatchResponse,
  AxiosError<AdminLinksControllerBatchError>,
  Options<AdminLinksControllerBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminLinksControllerBatchResponse,
    AxiosError<AdminLinksControllerBatchError>,
    Options<AdminLinksControllerBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminLinksControllerBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminLinksControllerBatchArchiveMutation = (
  options?: Partial<Options<AdminLinksControllerBatchArchiveData>>,
): UseMutationOptions<
  AdminLinksControllerBatchArchiveResponse,
  AxiosError<AdminLinksControllerBatchArchiveError>,
  Options<AdminLinksControllerBatchArchiveData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminLinksControllerBatchArchiveResponse,
    AxiosError<AdminLinksControllerBatchArchiveError>,
    Options<AdminLinksControllerBatchArchiveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminLinksControllerBatchArchive({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminLinksControllerArchiveMutation = (
  options?: Partial<Options<AdminLinksControllerArchiveData>>,
): UseMutationOptions<
  AdminLinksControllerArchiveResponse,
  AxiosError<AdminLinksControllerArchiveError>,
  Options<AdminLinksControllerArchiveData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminLinksControllerArchiveResponse,
    AxiosError<AdminLinksControllerArchiveError>,
    Options<AdminLinksControllerArchiveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminLinksControllerArchive({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminLinksControllerFindOneQueryKey = (
  options: Options<AdminLinksControllerFindOneData>,
) => createQueryKey('adminLinksControllerFindOne', options);

export const adminLinksControllerFindOneOptions = (
  options: Options<AdminLinksControllerFindOneData>,
) =>
  queryOptions<
    AdminLinksControllerFindOneResponse,
    AxiosError<AdminLinksControllerFindOneError>,
    AdminLinksControllerFindOneResponse,
    ReturnType<typeof adminLinksControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminLinksControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminLinksControllerFindOneQueryKey(options),
  });

export const adminLinksControllerUpdateMutation = (
  options?: Partial<Options<AdminLinksControllerUpdateData>>,
): UseMutationOptions<
  AdminLinksControllerUpdateResponse,
  AxiosError<AdminLinksControllerUpdateError>,
  Options<AdminLinksControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminLinksControllerUpdateResponse,
    AxiosError<AdminLinksControllerUpdateError>,
    Options<AdminLinksControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminLinksControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminLinksControllerRestoreMutation = (
  options?: Partial<Options<AdminLinksControllerRestoreData>>,
): UseMutationOptions<
  AdminLinksControllerRestoreResponse,
  AxiosError<AdminLinksControllerRestoreError>,
  Options<AdminLinksControllerRestoreData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminLinksControllerRestoreResponse,
    AxiosError<AdminLinksControllerRestoreError>,
    Options<AdminLinksControllerRestoreData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminLinksControllerRestore({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminSyncControllerListQueryKey = (
  options?: Options<AdminSyncControllerListData>,
) => createQueryKey('adminSyncControllerList', options);

export const adminSyncControllerListOptions = (
  options?: Options<AdminSyncControllerListData>,
) =>
  queryOptions<
    AdminSyncControllerListResponse,
    AxiosError<AdminSyncControllerListError>,
    AdminSyncControllerListResponse,
    ReturnType<typeof adminSyncControllerListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminSyncControllerList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminSyncControllerListQueryKey(options),
  });

export const adminSyncControllerListInfiniteQueryKey = (
  options?: Options<AdminSyncControllerListData>,
): QueryKey<Options<AdminSyncControllerListData>> =>
  createQueryKey('adminSyncControllerList', options, true);

export const adminSyncControllerListInfiniteOptions = (
  options?: Options<AdminSyncControllerListData>,
) =>
  infiniteQueryOptions<
    AdminSyncControllerListResponse,
    AxiosError<AdminSyncControllerListError>,
    InfiniteData<AdminSyncControllerListResponse>,
    QueryKey<Options<AdminSyncControllerListData>>,
    | number
    | Pick<
        QueryKey<Options<AdminSyncControllerListData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AdminSyncControllerListData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await adminSyncControllerList({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: adminSyncControllerListInfiniteQueryKey(options),
    },
  );

export const adminSyncControllerCreateMutation = (
  options?: Partial<Options<AdminSyncControllerCreateData>>,
): UseMutationOptions<
  AdminSyncControllerCreateResponse,
  AxiosError<AdminSyncControllerCreateError>,
  Options<AdminSyncControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminSyncControllerCreateResponse,
    AxiosError<AdminSyncControllerCreateError>,
    Options<AdminSyncControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminSyncControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminSyncControllerFindOneQueryKey = (
  options: Options<AdminSyncControllerFindOneData>,
) => createQueryKey('adminSyncControllerFindOne', options);

export const adminSyncControllerFindOneOptions = (
  options: Options<AdminSyncControllerFindOneData>,
) =>
  queryOptions<
    AdminSyncControllerFindOneResponse,
    AxiosError<AdminSyncControllerFindOneError>,
    AdminSyncControllerFindOneResponse,
    ReturnType<typeof adminSyncControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminSyncControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminSyncControllerFindOneQueryKey(options),
  });

export const adminTaxonomyControllerListQueryKey = (
  options: Options<AdminTaxonomyControllerListData>,
) => createQueryKey('adminTaxonomyControllerList', options);

export const adminTaxonomyControllerListOptions = (
  options: Options<AdminTaxonomyControllerListData>,
) =>
  queryOptions<
    AdminTaxonomyControllerListResponse,
    AxiosError<AdminTaxonomyControllerListError>,
    AdminTaxonomyControllerListResponse,
    ReturnType<typeof adminTaxonomyControllerListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminTaxonomyControllerList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminTaxonomyControllerListQueryKey(options),
  });

export const adminTaxonomyControllerCreateMutation = (
  options?: Partial<Options<AdminTaxonomyControllerCreateData>>,
): UseMutationOptions<
  AdminTaxonomyControllerCreateResponse,
  AxiosError<AdminTaxonomyControllerCreateError>,
  Options<AdminTaxonomyControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTaxonomyControllerCreateResponse,
    AxiosError<AdminTaxonomyControllerCreateError>,
    Options<AdminTaxonomyControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTaxonomyControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTaxonomyControllerRemoveMutation = (
  options?: Partial<Options<AdminTaxonomyControllerRemoveData>>,
): UseMutationOptions<
  AdminTaxonomyControllerRemoveResponse,
  AxiosError<AdminTaxonomyControllerRemoveError>,
  Options<AdminTaxonomyControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTaxonomyControllerRemoveResponse,
    AxiosError<AdminTaxonomyControllerRemoveError>,
    Options<AdminTaxonomyControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTaxonomyControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTaxonomyControllerRenameMutation = (
  options?: Partial<Options<AdminTaxonomyControllerRenameData>>,
): UseMutationOptions<
  AdminTaxonomyControllerRenameResponse,
  AxiosError<AdminTaxonomyControllerRenameError>,
  Options<AdminTaxonomyControllerRenameData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTaxonomyControllerRenameResponse,
    AxiosError<AdminTaxonomyControllerRenameError>,
    Options<AdminTaxonomyControllerRenameData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTaxonomyControllerRename({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerAccountQueryKey = (
  options?: Options<AdminTelegramControllerAccountData>,
) => createQueryKey('adminTelegramControllerAccount', options);

export const adminTelegramControllerAccountOptions = (
  options?: Options<AdminTelegramControllerAccountData>,
) =>
  queryOptions<
    AdminTelegramControllerAccountResponse,
    AxiosError<AdminTelegramControllerAccountError>,
    AdminTelegramControllerAccountResponse,
    ReturnType<typeof adminTelegramControllerAccountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminTelegramControllerAccount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminTelegramControllerAccountQueryKey(options),
  });

export const adminTelegramControllerSendCodeMutation = (
  options?: Partial<Options<AdminTelegramControllerSendCodeData>>,
): UseMutationOptions<
  AdminTelegramControllerSendCodeResponse,
  AxiosError<AdminTelegramControllerSendCodeError>,
  Options<AdminTelegramControllerSendCodeData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTelegramControllerSendCodeResponse,
    AxiosError<AdminTelegramControllerSendCodeError>,
    Options<AdminTelegramControllerSendCodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTelegramControllerSendCode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerVerifyCodeMutation = (
  options?: Partial<Options<AdminTelegramControllerVerifyCodeData>>,
): UseMutationOptions<
  AdminTelegramControllerVerifyCodeResponse,
  AxiosError<AdminTelegramControllerVerifyCodeError>,
  Options<AdminTelegramControllerVerifyCodeData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTelegramControllerVerifyCodeResponse,
    AxiosError<AdminTelegramControllerVerifyCodeError>,
    Options<AdminTelegramControllerVerifyCodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTelegramControllerVerifyCode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerVerifyPasswordMutation = (
  options?: Partial<Options<AdminTelegramControllerVerifyPasswordData>>,
): UseMutationOptions<
  AdminTelegramControllerVerifyPasswordResponse,
  AxiosError<AdminTelegramControllerVerifyPasswordError>,
  Options<AdminTelegramControllerVerifyPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTelegramControllerVerifyPasswordResponse,
    AxiosError<AdminTelegramControllerVerifyPasswordError>,
    Options<AdminTelegramControllerVerifyPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTelegramControllerVerifyPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerLogOutMutation = (
  options?: Partial<Options<AdminTelegramControllerLogOutData>>,
): UseMutationOptions<
  AdminTelegramControllerLogOutResponse,
  AxiosError<AdminTelegramControllerLogOutError>,
  Options<AdminTelegramControllerLogOutData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTelegramControllerLogOutResponse,
    AxiosError<AdminTelegramControllerLogOutError>,
    Options<AdminTelegramControllerLogOutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTelegramControllerLogOut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerRefreshChatsMutation = (
  options?: Partial<Options<AdminTelegramControllerRefreshChatsData>>,
): UseMutationOptions<
  AdminTelegramControllerRefreshChatsResponse,
  AxiosError<AdminTelegramControllerRefreshChatsError>,
  Options<AdminTelegramControllerRefreshChatsData>
> => {
  const mutationOptions: UseMutationOptions<
    AdminTelegramControllerRefreshChatsResponse,
    AxiosError<AdminTelegramControllerRefreshChatsError>,
    Options<AdminTelegramControllerRefreshChatsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await adminTelegramControllerRefreshChats({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminTelegramControllerListChatsQueryKey = (
  options?: Options<AdminTelegramControllerListChatsData>,
) => createQueryKey('adminTelegramControllerListChats', options);

export const adminTelegramControllerListChatsOptions = (
  options?: Options<AdminTelegramControllerListChatsData>,
) =>
  queryOptions<
    AdminTelegramControllerListChatsResponse,
    AxiosError<AdminTelegramControllerListChatsError>,
    AdminTelegramControllerListChatsResponse,
    ReturnType<typeof adminTelegramControllerListChatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminTelegramControllerListChats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminTelegramControllerListChatsQueryKey(options),
  });

export const adminTelegramControllerListChatsInfiniteQueryKey = (
  options?: Options<AdminTelegramControllerListChatsData>,
): QueryKey<Options<AdminTelegramControllerListChatsData>> =>
  createQueryKey('adminTelegramControllerListChats', options, true);

export const adminTelegramControllerListChatsInfiniteOptions = (
  options?: Options<AdminTelegramControllerListChatsData>,
) =>
  infiniteQueryOptions<
    AdminTelegramControllerListChatsResponse,
    AxiosError<AdminTelegramControllerListChatsError>,
    InfiniteData<AdminTelegramControllerListChatsResponse>,
    QueryKey<Options<AdminTelegramControllerListChatsData>>,
    | number
    | Pick<
        QueryKey<Options<AdminTelegramControllerListChatsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<AdminTelegramControllerListChatsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await adminTelegramControllerListChats({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: adminTelegramControllerListChatsInfiniteQueryKey(options),
    },
  );

export const adminTelegramControllerScanOptionsQueryKey = (
  options?: Options<AdminTelegramControllerScanOptionsData>,
) => createQueryKey('adminTelegramControllerScanOptions', options);

export const adminTelegramControllerScanOptionsOptions = (
  options?: Options<AdminTelegramControllerScanOptionsData>,
) =>
  queryOptions<
    AdminTelegramControllerScanOptionsResponse,
    AxiosError<AdminTelegramControllerScanOptionsError>,
    AdminTelegramControllerScanOptionsResponse,
    ReturnType<typeof adminTelegramControllerScanOptionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminTelegramControllerScanOptions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminTelegramControllerScanOptionsQueryKey(options),
  });
