// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorResponseDtoSchema = {
  type: 'object',
  properties: {
    statusCode: {
      type: 'number',
      example: 400,
    },
    code: {
      type: 'string',
      example: 'VALIDATION_ERROR',
    },
    message: {
      type: 'string',
      example: '请求参数校验失败。',
    },
    details: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
    path: {
      type: 'string',
      example: '/api/admin/v1/links',
    },
    timestamp: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['statusCode', 'code', 'message', 'path', 'timestamp'],
} as const;

export const OverviewCountResponseDtoSchema = {
  type: 'object',
  properties: {
    count: {
      type: 'number',
    },
    id: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: 'string',
    },
  },
  required: ['count', 'id', 'name'],
} as const;

export const WebOverviewCountsResponseDtoSchema = {
  type: 'object',
  properties: {
    pending: {
      type: 'number',
    },
    recent: {
      type: 'number',
    },
    total: {
      type: 'number',
    },
  },
  required: ['pending', 'recent', 'total'],
} as const;

export const WebLatestSyncResponseDtoSchema = {
  type: 'object',
  properties: {
    finishedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    status: {
      type: 'string',
      enum: [
        'queued',
        'running',
        'succeeded',
        'partiallySucceeded',
        'failed',
        'interrupted',
      ],
    },
  },
  required: ['finishedAt', 'status'],
} as const;

export const WebOverviewResponseDtoSchema = {
  type: 'object',
  properties: {
    categories: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OverviewCountResponseDto',
      },
    },
    counts: {
      $ref: '#/components/schemas/WebOverviewCountsResponseDto',
    },
    latestSync: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/WebLatestSyncResponseDto',
        },
      ],
    },
    projects: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/OverviewCountResponseDto',
      },
    },
  },
  required: ['categories', 'counts', 'latestSync', 'projects'],
} as const;

export const TaxonomyReferenceResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: 'string',
    },
  },
  required: ['id', 'name'],
} as const;

export const LinkSourceResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    chatId: {
      type: 'string',
      format: 'uuid',
    },
    chatName: {
      type: 'string',
    },
    messageId: {
      type: 'number',
    },
    messagePreview: {
      type: 'string',
    },
    messageText: {
      type: 'string',
    },
    messageUrl: {
      type: 'string',
      nullable: true,
    },
    rawUrl: {
      type: 'string',
    },
    senderName: {
      type: 'string',
      nullable: true,
    },
    capturedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: [
    'id',
    'chatId',
    'chatName',
    'messageId',
    'messagePreview',
    'rawUrl',
    'capturedAt',
  ],
} as const;

export const LinkResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    domain: {
      type: 'string',
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    project: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
        },
      ],
    },
    category: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
        },
      ],
    },
    tags: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/TaxonomyReferenceResponseDto',
      },
    },
    purpose: {
      type: 'string',
      nullable: true,
    },
    sourceCount: {
      type: 'number',
    },
    latestSource: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/LinkSourceResponseDto',
        },
      ],
    },
    sources: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/LinkSourceResponseDto',
      },
    },
    firstDiscoveredAt: {
      type: 'string',
      format: 'date-time',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
    archivedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
  },
  required: [
    'id',
    'title',
    'url',
    'domain',
    'environment',
    'status',
    'project',
    'category',
    'tags',
    'purpose',
    'sourceCount',
    'latestSource',
    'firstDiscoveredAt',
    'createdAt',
    'updatedAt',
    'archivedAt',
  ],
} as const;

export const PaginationMetaResponseDtoSchema = {
  type: 'object',
  properties: {
    page: {
      type: 'number',
    },
    pageSize: {
      type: 'number',
    },
    total: {
      type: 'number',
    },
    totalPages: {
      type: 'number',
    },
  },
  required: ['page', 'pageSize', 'total', 'totalPages'],
} as const;

export const PaginatedLinksResponseDtoSchema = {
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/LinkResponseDto',
      },
    },
    pagination: {
      $ref: '#/components/schemas/PaginationMetaResponseDto',
    },
  },
  required: ['items', 'pagination'],
} as const;

export const LatestSyncSummaryResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    status: {
      type: 'string',
      enum: [
        'queued',
        'running',
        'succeeded',
        'partiallySucceeded',
        'failed',
        'interrupted',
      ],
    },
    finishedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['id', 'status', 'finishedAt', 'createdAt'],
} as const;

export const AdminOverviewResponseDtoSchema = {
  type: 'object',
  properties: {
    archived: {
      type: 'number',
    },
    latestSync: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/LatestSyncSummaryResponseDto',
        },
      ],
    },
    pending: {
      type: 'number',
    },
    todayAdded: {
      type: 'number',
    },
    total: {
      type: 'number',
    },
  },
  required: ['archived', 'latestSync', 'pending', 'todayAdded', 'total'],
} as const;

export const BatchLinkPatchDtoSchema = {
  type: 'object',
  properties: {
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    purpose: {
      type: 'string',
      nullable: true,
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    projectId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    categoryId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    tagIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
    addTagIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
  },
} as const;

export const BatchUpdateLinksDtoSchema = {
  type: 'object',
  properties: {
    ids: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
    patch: {
      $ref: '#/components/schemas/BatchLinkPatchDto',
    },
  },
  required: ['ids', 'patch'],
} as const;

export const BatchSkippedLinkResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    code: {
      type: 'string',
    },
    message: {
      type: 'string',
    },
  },
  required: ['id', 'code', 'message'],
} as const;

export const BatchUpdateLinksResponseDtoSchema = {
  type: 'object',
  properties: {
    updatedIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
    skipped: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/BatchSkippedLinkResponseDto',
      },
    },
  },
  required: ['updatedIds', 'skipped'],
} as const;

export const UpdateLinkDtoSchema = {
  type: 'object',
  properties: {
    title: {
      type: 'string',
    },
    url: {
      type: 'string',
    },
    purpose: {
      type: 'string',
      nullable: true,
    },
    environment: {
      type: 'string',
      enum: ['production', 'test', 'development', 'unknown'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'organized'],
    },
    projectId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    categoryId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    tagIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
  },
} as const;

export const CreateSyncJobDtoSchema = {
  type: 'object',
  properties: {
    chatIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
    rangeMode: {
      type: 'string',
      enum: ['sinceLast', 'last7Days', 'custom', 'allHistory'],
    },
    rangeFrom: {
      type: 'string',
      format: 'date-time',
    },
    rangeTo: {
      type: 'string',
      format: 'date-time',
    },
    defaultProjectId: {
      type: 'string',
      format: 'uuid',
    },
    defaultCategoryId: {
      type: 'string',
      format: 'uuid',
    },
    defaultTagIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
  },
  required: ['rangeMode'],
} as const;

export const SyncJobChatResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    chatId: {
      type: 'string',
      format: 'uuid',
    },
    chatTitle: {
      type: 'string',
    },
    status: {
      type: 'string',
      enum: ['pending', 'running', 'succeeded', 'failed'],
    },
    messageCount: {
      type: 'number',
    },
    foundCount: {
      type: 'number',
    },
    newCount: {
      type: 'number',
    },
    duplicateCount: {
      type: 'number',
    },
    maxProcessedMessageId: {
      type: 'number',
      nullable: true,
    },
    error: {
      type: 'string',
      nullable: true,
    },
    startedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    finishedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
  },
  required: [
    'id',
    'chatId',
    'chatTitle',
    'status',
    'messageCount',
    'foundCount',
    'newCount',
    'duplicateCount',
    'maxProcessedMessageId',
    'error',
    'startedAt',
    'finishedAt',
  ],
} as const;

export const SyncJobResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    status: {
      type: 'string',
      enum: [
        'queued',
        'running',
        'succeeded',
        'partiallySucceeded',
        'failed',
        'interrupted',
      ],
    },
    stage: {
      type: 'string',
      enum: [
        'connecting',
        'reading',
        'extracting',
        'deduplicating',
        'saving',
        null,
      ],
      nullable: true,
    },
    progress: {
      type: 'number',
    },
    rangeMode: {
      type: 'string',
      enum: ['sinceLast', 'last7Days', 'custom', 'allHistory'],
    },
    rangeFrom: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    rangeTo: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    defaultProjectId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    defaultCategoryId: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    defaultTagIds: {
      type: 'array',
      items: {
        type: 'string',
        format: 'uuid',
      },
    },
    messageCount: {
      type: 'number',
    },
    foundCount: {
      type: 'number',
    },
    newCount: {
      type: 'number',
    },
    duplicateCount: {
      type: 'number',
    },
    error: {
      type: 'string',
      nullable: true,
    },
    startedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    finishedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
    chats: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/SyncJobChatResponseDto',
      },
    },
  },
  required: [
    'id',
    'status',
    'stage',
    'progress',
    'rangeMode',
    'rangeFrom',
    'rangeTo',
    'defaultProjectId',
    'defaultCategoryId',
    'defaultTagIds',
    'messageCount',
    'foundCount',
    'newCount',
    'duplicateCount',
    'error',
    'startedAt',
    'finishedAt',
    'createdAt',
    'updatedAt',
    'chats',
  ],
} as const;

export const PaginatedSyncJobsResponseDtoSchema = {
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/SyncJobResponseDto',
      },
    },
    pagination: {
      $ref: '#/components/schemas/PaginationMetaResponseDto',
    },
  },
  required: ['items', 'pagination'],
} as const;

export const TaxonomyItemResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: 'string',
    },
    referenceCount: {
      type: 'number',
    },
  },
  required: ['id', 'name', 'referenceCount'],
} as const;

export const TaxonomyNameDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
  },
  required: ['name'],
} as const;

export const TelegramAccountProfileResponseDtoSchema = {
  type: 'object',
  properties: {
    displayName: {
      type: 'string',
      nullable: true,
    },
    phoneNumber: {
      type: 'string',
      nullable: true,
    },
    telegramUserId: {
      type: 'string',
      nullable: true,
    },
    username: {
      type: 'string',
      nullable: true,
    },
  },
  required: ['displayName', 'phoneNumber', 'telegramUserId', 'username'],
} as const;

export const TelegramAccountResponseDtoSchema = {
  type: 'object',
  properties: {
    configured: {
      type: 'boolean',
    },
    status: {
      type: 'string',
      enum: ['authorized', 'unauthorized'],
    },
    account: {
      nullable: true,
      type: 'object',
      allOf: [
        {
          $ref: '#/components/schemas/TelegramAccountProfileResponseDto',
        },
      ],
    },
  },
  required: ['configured', 'status', 'account'],
} as const;

export const SendCodeDtoSchema = {
  type: 'object',
  properties: {
    phoneNumber: {
      type: 'string',
      example: '+8613800000000',
    },
  },
  required: ['phoneNumber'],
} as const;

export const SendCodeResponseDtoSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
    delivery: {
      type: 'string',
      enum: ['app', 'sms'],
    },
    expiresAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['challengeId', 'delivery', 'expiresAt'],
} as const;

export const VerifyCodeDtoSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['challengeId'],
} as const;

export const TelegramAuthResultResponseDtoSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
      enum: ['authorized', 'passwordRequired'],
    },
  },
  required: ['status'],
} as const;

export const VerifyPasswordDtoSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
  },
  required: ['challengeId'],
} as const;

export const RefreshChatsResponseDtoSchema = {
  type: 'object',
  properties: {
    count: {
      type: 'number',
    },
    refreshedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: ['count', 'refreshedAt'],
} as const;

export const TelegramChatResponseDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    telegramPeerId: {
      type: 'string',
    },
    type: {
      type: 'string',
      enum: ['saved', 'private', 'group', 'channel'],
    },
    title: {
      type: 'string',
    },
    username: {
      type: 'string',
      nullable: true,
    },
    isEnabled: {
      type: 'boolean',
    },
    isAvailable: {
      type: 'boolean',
    },
    lastSyncedMessageId: {
      type: 'number',
      nullable: true,
    },
    lastSyncedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
    },
  },
  required: [
    'id',
    'telegramPeerId',
    'type',
    'title',
    'username',
    'isEnabled',
    'isAvailable',
    'lastSyncedMessageId',
    'lastSyncedAt',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const PaginatedTelegramChatsResponseDtoSchema = {
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/TelegramChatResponseDto',
      },
    },
    pagination: {
      $ref: '#/components/schemas/PaginationMetaResponseDto',
    },
  },
  required: ['items', 'pagination'],
} as const;

export const UpdateChatDtoSchema = {
  type: 'object',
  properties: {
    isEnabled: {
      type: 'boolean',
    },
  },
  required: ['isEnabled'],
} as const;

export const VerifyCodeDtoWritableSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
    code: {
      type: 'string',
      writeOnly: true,
    },
  },
  required: ['challengeId', 'code'],
} as const;

export const VerifyPasswordDtoWritableSchema = {
  type: 'object',
  properties: {
    challengeId: {
      type: 'string',
      format: 'uuid',
    },
    password: {
      type: 'string',
      writeOnly: true,
    },
  },
  required: ['challengeId', 'password'],
} as const;
