// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  WebApiControllerFindOneData,
  WebApiControllerFindOneResponses,
  WebApiControllerListData,
  WebApiControllerListResponses,
  WebApiControllerOverviewData,
  WebApiControllerOverviewResponses,
} from './types.gen';
import {
  zWebApiControllerFindOneResponse,
  zWebApiControllerListResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const webApiControllerOverview = <ThrowOnError extends boolean = false>(
  options?: Options<WebApiControllerOverviewData, ThrowOnError>,
): RequestResult<WebApiControllerOverviewResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    WebApiControllerOverviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/web/v1/overview', ...options });

export const webApiControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<WebApiControllerListData, ThrowOnError>,
): RequestResult<WebApiControllerListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    WebApiControllerListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zWebApiControllerListResponse.parseAsync(data),
    url: '/api/web/v1/links',
    ...options,
  });

export const webApiControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<WebApiControllerFindOneData, ThrowOnError>,
): RequestResult<WebApiControllerFindOneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    WebApiControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    responseValidator: async (data) =>
      await zWebApiControllerFindOneResponse.parseAsync(data),
    url: '/api/web/v1/links/{id}',
    ...options,
  });
