// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type Object = {
  [key: string]: unknown;
};

export type TaxonomyReferenceResponseDto = {
  id: string;
  name: string;
};

export type LinkSourceResponseDto = {
  id: string;
  chatId: string;
  chatName: string;
  messageId: number;
  messagePreview: string;
  messageText?: string;
  messageUrl?: {
    [key: string]: unknown;
  } | null;
  rawUrl: string;
  senderName?: {
    [key: string]: unknown;
  } | null;
  capturedAt: string;
};

export type LinkResponseDto = {
  id: string;
  title: string;
  url: string;
  domain: string;
  environment: 'production' | 'test' | 'development' | 'unknown';
  status: 'pending' | 'organized';
  project: TaxonomyReferenceResponseDto | null;
  category: TaxonomyReferenceResponseDto | null;
  tags: Array<TaxonomyReferenceResponseDto>;
  purpose: {
    [key: string]: unknown;
  } | null;
  isFavorite: boolean;
  sourceCount: number;
  latestSource: LinkSourceResponseDto | null;
  sources?: Array<LinkSourceResponseDto>;
  firstDiscoveredAt: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: {
    [key: string]: unknown;
  } | null;
};

export type PaginationMetaResponseDto = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
};

export type PaginatedLinksResponseDto = {
  items: Array<LinkResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type BatchLinkPatchDto = {
  title?: string;
  url?: string;
  purpose?: {
    [key: string]: unknown;
  } | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: {
    [key: string]: unknown;
  } | null;
  categoryId?: {
    [key: string]: unknown;
  } | null;
  tagIds?: Array<Array<unknown>>;
  isFavorite?: boolean;
  addTagIds?: Array<Array<unknown>>;
};

export type BatchUpdateLinksDto = {
  ids: Array<Array<unknown>>;
  patch: BatchLinkPatchDto;
};

export type UpdateLinkDto = {
  title?: string;
  url?: string;
  purpose?: {
    [key: string]: unknown;
  } | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: {
    [key: string]: unknown;
  } | null;
  categoryId?: {
    [key: string]: unknown;
  } | null;
  tagIds?: Array<Array<unknown>>;
  isFavorite?: boolean;
};

export type CreateSyncJobDto = {
  chatIds?: Array<Array<unknown>>;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom?: string;
  rangeTo?: string;
  defaultProjectId?: string;
  defaultCategoryId?: string;
  defaultTagIds?: Array<Array<unknown>>;
};

export type TaxonomyNameDto = {
  name: string;
};

export type SendCodeDto = {
  phoneNumber: string;
};

export type VerifyCodeDto = {
  challengeId: string;
};

export type VerifyPasswordDto = {
  challengeId: string;
};

export type UpdateChatDto = {
  isEnabled: boolean;
};

export type ObjectWritable = {
  [key: string]: unknown;
};

export type VerifyCodeDtoWritable = {
  challengeId: string;
  code: string;
};

export type VerifyPasswordDtoWritable = {
  challengeId: string;
  password: string;
};

export type WebApiControllerOverviewData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/web/v1/overview';
};

export type WebApiControllerOverviewResponses = {
  /**
   * Web 链接工作台概览。
   */
  200: unknown;
};

export type WebApiControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: ObjectWritable;
    pageSize?: ObjectWritable;
    q?: string;
    view?: 'all' | 'recent' | 'favorites' | 'pending';
    /**
     * UUID 或 unassigned
     */
    projectId?: string;
    categoryId?: string;
    environment?: 'production' | 'test' | 'development' | 'unknown';
    status?: 'pending' | 'organized';
    sort?: 'newest' | 'oldest' | 'title';
    sourceChatId?: string;
    tagIds?: Array<string>;
    includeArchived?: boolean;
  };
  url: '/api/web/v1/links';
};

export type WebApiControllerListResponses = {
  200: PaginatedLinksResponseDto;
};

export type WebApiControllerListResponse =
  WebApiControllerListResponses[keyof WebApiControllerListResponses];

export type WebApiControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/web/v1/links/{id}';
};

export type WebApiControllerFindOneResponses = {
  200: LinkResponseDto;
};

export type WebApiControllerFindOneResponse =
  WebApiControllerFindOneResponses[keyof WebApiControllerFindOneResponses];
