// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type ApiErrorResponseDto = {
  statusCode: number;
  code: string;
  message: string;
  details?: Array<string>;
  path: string;
  timestamp: string;
};

export type OverviewCountResponseDto = {
  count: number;
  id: string;
  name: string;
};

export type WebOverviewCountsResponseDto = {
  favorites: number;
  pending: number;
  recent: number;
  total: number;
};

export type WebLatestSyncResponseDto = {
  finishedAt: string | null;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
};

export type WebOverviewResponseDto = {
  categories: Array<OverviewCountResponseDto>;
  counts: WebOverviewCountsResponseDto;
  latestSync: WebLatestSyncResponseDto | null;
  projects: Array<OverviewCountResponseDto>;
};

export type TaxonomyReferenceResponseDto = {
  id: string;
  name: string;
};

export type LinkSourceResponseDto = {
  id: string;
  chatId: string;
  chatName: string;
  messageId: number;
  messagePreview: string;
  messageText?: string;
  messageUrl?: string | null;
  rawUrl: string;
  senderName?: string | null;
  capturedAt: string;
};

export type LinkResponseDto = {
  id: string;
  title: string;
  url: string;
  domain: string;
  environment: 'production' | 'test' | 'development' | 'unknown';
  status: 'pending' | 'organized';
  project: TaxonomyReferenceResponseDto | null;
  category: TaxonomyReferenceResponseDto | null;
  tags: Array<TaxonomyReferenceResponseDto>;
  purpose: string | null;
  isFavorite: boolean;
  sourceCount: number;
  latestSource: LinkSourceResponseDto | null;
  sources?: Array<LinkSourceResponseDto>;
  firstDiscoveredAt: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
};

export type PaginationMetaResponseDto = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
};

export type PaginatedLinksResponseDto = {
  items: Array<LinkResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type LatestSyncSummaryResponseDto = {
  id: string;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
  finishedAt: string | null;
  createdAt: string;
};

export type AdminOverviewResponseDto = {
  archived: number;
  latestSync: LatestSyncSummaryResponseDto | null;
  pending: number;
  todayAdded: number;
  total: number;
};

export type BatchLinkPatchDto = {
  title?: string;
  url?: string;
  purpose?: string | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: string | null;
  categoryId?: string | null;
  tagIds?: Array<string>;
  isFavorite?: boolean;
  addTagIds?: Array<string>;
};

export type BatchUpdateLinksDto = {
  ids: Array<string>;
  patch: BatchLinkPatchDto;
};

export type BatchSkippedLinkResponseDto = {
  id: string;
  code: string;
  message: string;
};

export type BatchUpdateLinksResponseDto = {
  updatedIds: Array<string>;
  skipped: Array<BatchSkippedLinkResponseDto>;
};

export type UpdateLinkDto = {
  title?: string;
  url?: string;
  purpose?: string | null;
  environment?: 'production' | 'test' | 'development' | 'unknown';
  status?: 'pending' | 'organized';
  projectId?: string | null;
  categoryId?: string | null;
  tagIds?: Array<string>;
  isFavorite?: boolean;
};

export type CreateSyncJobDto = {
  chatIds?: Array<string>;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom?: string;
  rangeTo?: string;
  defaultProjectId?: string;
  defaultCategoryId?: string;
  defaultTagIds?: Array<string>;
};

export type SyncJobChatResponseDto = {
  id: string;
  chatId: string;
  chatTitle: string;
  status: 'pending' | 'running' | 'succeeded' | 'failed';
  messageCount: number;
  foundCount: number;
  newCount: number;
  duplicateCount: number;
  maxProcessedMessageId: number | null;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
};

export type SyncJobResponseDto = {
  id: string;
  status:
    | 'queued'
    | 'running'
    | 'succeeded'
    | 'partiallySucceeded'
    | 'failed'
    | 'interrupted';
  stage:
    | 'connecting'
    | 'reading'
    | 'extracting'
    | 'deduplicating'
    | 'saving'
    | null;
  progress: number;
  rangeMode: 'sinceLast' | 'last7Days' | 'custom' | 'allHistory';
  rangeFrom: string | null;
  rangeTo: string | null;
  defaultProjectId: string | null;
  defaultCategoryId: string | null;
  defaultTagIds: Array<string>;
  messageCount: number;
  foundCount: number;
  newCount: number;
  duplicateCount: number;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  chats: Array<SyncJobChatResponseDto>;
};

export type PaginatedSyncJobsResponseDto = {
  items: Array<SyncJobResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type TaxonomyItemResponseDto = {
  id: string;
  name: string;
  referenceCount: number;
};

export type TaxonomyNameDto = {
  name: string;
};

export type TelegramAccountProfileResponseDto = {
  displayName: string | null;
  phoneNumber: string | null;
  telegramUserId: string | null;
  username: string | null;
};

export type TelegramAccountResponseDto = {
  configured: boolean;
  status: 'authorized' | 'unauthorized';
  account: TelegramAccountProfileResponseDto | null;
};

export type SendCodeDto = {
  phoneNumber: string;
};

export type SendCodeResponseDto = {
  challengeId: string;
  delivery: 'app' | 'sms';
  expiresAt: string;
};

export type VerifyCodeDto = {
  challengeId: string;
};

export type TelegramAuthResultResponseDto = {
  status: 'authorized' | 'passwordRequired';
};

export type VerifyPasswordDto = {
  challengeId: string;
};

export type RefreshChatsResponseDto = {
  count: number;
  refreshedAt: string;
};

export type TelegramChatResponseDto = {
  id: string;
  telegramPeerId: string;
  type: 'saved' | 'private' | 'group' | 'channel';
  title: string;
  username: string | null;
  isEnabled: boolean;
  isAvailable: boolean;
  lastSyncedMessageId: number | null;
  lastSyncedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PaginatedTelegramChatsResponseDto = {
  items: Array<TelegramChatResponseDto>;
  pagination: PaginationMetaResponseDto;
};

export type UpdateChatDto = {
  isEnabled: boolean;
};

export type VerifyCodeDtoWritable = {
  challengeId: string;
  code: string;
};

export type VerifyPasswordDtoWritable = {
  challengeId: string;
  password: string;
};

export type WebApiControllerOverviewData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/web/v1/overview';
};

export type WebApiControllerOverviewErrors = {
  400: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type WebApiControllerOverviewError =
  WebApiControllerOverviewErrors[keyof WebApiControllerOverviewErrors];

export type WebApiControllerOverviewResponses = {
  200: WebOverviewResponseDto;
};

export type WebApiControllerOverviewResponse =
  WebApiControllerOverviewResponses[keyof WebApiControllerOverviewResponses];

export type WebApiControllerListData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    q?: string;
    view?: 'all' | 'recent' | 'favorites' | 'pending';
    /**
     * UUID 或 unassigned
     */
    projectId?: string;
    categoryId?: string;
    environment?: 'production' | 'test' | 'development' | 'unknown';
    status?: 'pending' | 'organized';
    sort?: 'newest' | 'oldest' | 'title';
    sourceChatId?: string;
    tagIds?: Array<string>;
    includeArchived?: boolean;
  };
  url: '/api/web/v1/links';
};

export type WebApiControllerListErrors = {
  400: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type WebApiControllerListError =
  WebApiControllerListErrors[keyof WebApiControllerListErrors];

export type WebApiControllerListResponses = {
  200: PaginatedLinksResponseDto;
};

export type WebApiControllerListResponse =
  WebApiControllerListResponses[keyof WebApiControllerListResponses];

export type WebApiControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/web/v1/links/{id}';
};

export type WebApiControllerFindOneErrors = {
  400: ApiErrorResponseDto;
  404: ApiErrorResponseDto;
  409: ApiErrorResponseDto;
  500: ApiErrorResponseDto;
};

export type WebApiControllerFindOneError =
  WebApiControllerFindOneErrors[keyof WebApiControllerFindOneErrors];

export type WebApiControllerFindOneResponses = {
  200: LinkResponseDto;
};

export type WebApiControllerFindOneResponse =
  WebApiControllerFindOneResponses[keyof WebApiControllerFindOneResponses];
